### ISSUE TITLE
Could add migration guide into wiki

### ISSUE THREAD

**Issue by Jortana** [thijsvanloef/palworld-server-docker#100]
I think it would be useful to add a guide on the wiki about how to migrate existing saves to Docker.

I have tried the method of migrating server saves from a Windows environment to Docker. Here is my steps:

1. Copy the save from your old dedicated server to your new dedicated server.
2. In the `PalServer\Pal\Saved\Config\LinuxServer\GameUserSettings.ini` file of the new server, change the `DedicatedServerName` to match your save's folder name. For example, if your save's folder name is `2E85FD38BAA792EB1D4C09386F3A3CDA`, the `DedicatedServerName` changes to `DedicatedServerName=2E85FD38BAA792EB1D4C09386F3A3CDA`.
3. Delete the entire new server save at `PalServer\Pal\Saved\SaveGames\0\<your_save_here>`, and replace it with the folder from the old server.
4. Restart the new server and have fun.

[This repository](https://github.com/xNul/palworld-host-save-fix) could be helpful. However, I didn't migrate my saves according to the guide in the repository. My intuition told me it didn't need to be that complicated, and indeed, the outcome proved I was right.

**Comment by Ericwww** [comment]
I think add some guide would be helpful. 😃 😃 👍 

Also, I'm taking effort to write a script so that we can migrate simplefully.

However, the prerequisite is that the migration solution we have is authentic and effective.
