### ISSUE TITLE
RCON didt show anything

### ISSUE THREAD

**Issue by DeArchX** [thijsvanloef/palworld-server-docker#102]
## Describe the bug

RCON-cli didt show anything

## To Reproduce

docker exec -it palworld-server rcon-cli
Info

## Expected behavior

Show the info of server

## Screenshots

![image](https://github.com/thijsvanloef/palworld-server-docker/assets/145952424/4923a157-7c4b-4d54-9995-4c905598ac24)

## Desktop (please complete the following information)

- OS:Ubuntu 22.04

**Comment by thijsvanloef** [comment]
@DeArchX I am not able to reproduce this error, please make sure that you are running the latest version of my image using the following commands:

- `docker compose down --rmi all`
- `docker compose up -d`

**Comment by DeArchX** [comment]
My server name includes chinese, So my theory is this is same problem as #97

**Comment by thijsvanloef** [comment]
@DeArchX ah right, someone else is currently looking into updating rcon to a different binary, hopefully that will fix this issue. But from my understanding it also has issues supporting different characters

**Comment by thijsvanloef** [comment]
@DeArchX I've just merged the RCON update, could you update to the latest image and check again?

**Comment by DeArchX** [comment]
Sorry for the late, But it didnt work after i pull the latest image
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/145952424/e8bd6e7b-e08d-4f95-b4dd-d163657a1337)

**Comment by thijsvanloef** [comment]
It seems like the rcon-cli package does not support the chinese language, I would suggest opening an issue here: https://github.com/gorcon/rcon-cli

**Comment by DeArchX** [comment]
> It seems like the rcon-cli package does not support the chinese language, I would suggest opening an issue here: https://github.com/gorcon/rcon-cli

Ok, Thanks for you great works again!
