### ISSUE TITLE
how do i reboot?

### ISSUE THREAD

**Issue by cornradio** [thijsvanloef/palworld-server-docker#103]
how do i reboot?
Any changes made there will be applied to the Server on **next boot**
should I rm -f my docker and start it again?

**Comment by thijsvanloef** [comment]
- `docker compose restart' 
:smile:

**Comment by cornradio** [comment]
> `docker compose restart` 😄

ok i figure out , and thankyou!
 i used docker run Not docker compose

```
docker ps
0d41b1c99ad6   thijsvanloef/palworld-server-docker

docker restart 0d41b1c99ad6
```

and I can change config this way:
```
find / -name PalWorldSettings.ini

vim /var/lib/docker/volumes/54e7bd25628ea77ca06bdd7a0cb9f5819eb0c83835d039d625a0d2b19d0bd4c1/_data/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini
```
