### ISSUE TITLE
Game progress is lost after server restart

### ISSUE THREAD

**Issue by chenjx56** [thijsvanloef/palworld-server-docker#105]
## Game progress is lost after server restart
I update my steamcmd today and my game save is rolled back to the last time the server was started.
Strangely enough, my in-game technology was kept up to date.

## To Reproduce

1. ``docker restart container_id'' to restart the server
2. connect to the server

## Expected behavior

Go back to the game progress before restarting the server.

## Screenshots

![image](https://github.com/thijsvanloef/palworld-server-docker/assets/54338601/49db8fbd-de7d-452d-8647-e391d4a4cae1)
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/54338601/8c236830-dfa8-4c5b-8a58-59758e37e470)

## Desktop (please complete the following information)

- OS: Ubuntu
- Browser chrome
- Version 22

## docker-compose.yml contents

I do not change anything, and build the docker with this command: "docker build --tag pal_server"

## Container/Host Logs

everything is ok.

## Additional context

Nothing.

**Comment by raimannma** [comment]
Did you mounted a volume to the container?

**Comment by fryfrog** [comment]
Show your compose or `docker run`.

**Comment by Dashboy1998** [comment]
What version of this were you running?

**Comment by chenjx56** [comment]
> Did you mounted a volume to the container?

yes, i use the docker run command in the readMe file.

**Comment by chenjx56** [comment]
> Show your compose or `docker run`.

i use the docker run command which is same with the readme

**Comment by chenjx56** [comment]
> What version of this were you running?

0.13.0

**Comment by Dashboy1998** [comment]
> I update my steamcmd today and my game save is rolled back to the last time the server was started.
> Strangely enough, my in-game technology was kept up to date.

This is because the game appears to constantly save player data but periodically (Not sure how often) save world data.

This was fixed by #98 if rcon is enabled. Otherwise you have to run the save command manually. If you do not have rcon enabled I recommend stopping the server (and container) by issuing the save command the shutdown command in game.

Note currently backups do not run the save command, I added a fix in #118.

**Comment by chenjx56** [comment]
> > I update my steamcmd today and my game save is rolled back to the last time the server was started.
> > Strangely enough, my in-game technology was kept up to date.
> 
> This is because the game appears to constantly save player data but periodically (Not sure how often) save world data.
> 
> This was fixed by #98 if rcon is enabled. Otherwise you have to run the save command manually. If you do not have rcon enabled I recommend stopping the server (and container) by issuing the save command the shutdown command in game. That merge is in version 0.14.0.
> 
> Note currently backups do not run the save command, I added a fix in #118.

thank you so much, I can not reproduce this issue, but I will use the save command in the game.

**Comment by thijsvanloef** [comment]
@chenjx56 has your issue been resolved?

**Comment by chenjx56** [comment]
> @chenjx56 has your issue been resolved?

Yes, thank you very much, I will close the issue.
