### ISSUE TITLE
Chose specific version?

### ISSUE THREAD

**Issue by crazynds** [thijsvanloef/palworld-server-docker#106]
There is a way to chose a specif version to the server run?

**Comment by FurkanVG** [comment]
Why would you want this? The client side needs to be always the same like the server side. And since all client users use Steam, it auto-updates the client side. For these you need to ensure your server-side is also update.

**Comment by fryfrog** [comment]
It might make sense if they ever have a stable and beta version, kind of like Satisfactory. But probably not now when there is really just the latest version.

**Comment by thijsvanloef** [comment]
This is not possible currently, and not a feature I am planning to support
