### ISSUE TITLE
Someone fixed the memory leak

### ISSUE THREAD

**Issue by YinBuLiao** [thijsvanloef/palworld-server-docker#109]
Someone fixed the memory leak
Here is his repository link
https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix

**Comment by fryfrog** [comment]
😬 

Hopefully the palworld devs see this and incorporate it. I can't imagine pulling some random server binary into a docker image many people are using!

**Comment by thijsvanloef** [comment]
I have to agree with @fryfrog, as much as I want the memory leak resolved, I believe I should not be the one responsible for that.

**Comment by Derisat** [comment]
how do i use the files at that link, im a laymen. running a linux based seservervrer from skynode
