### ISSUE TITLE
Subject: Request: Include Server Requirements in README

### ISSUE THREAD

**Issue by Apollo55** [thijsvanloef/palworld-server-docker#110]
Hi there,

Great job on the project! I have a quick suggestion: can we add the hardware requirements to the README.txt? It would be super helpful for users.

Thanks a bunch!

Best,

Martin.

**Comment by fryfrog** [comment]
A link to palworld's own dedicated server documentation would probably be better since their requirements are likely to evolve as it gets developed.

**Comment by thijsvanloef** [comment]
Done!
