### ISSUE TITLE
Rcon cli disconnects all by itself

### ISSUE THREAD

**Issue by Dylseat** [thijsvanloef/palworld-server-docker#113]
## Describe the bug

sometime Rcon cli disconnects all by itself

## To Reproduce

execute this command: docker exec -it palworld-server rcon-cli
use broadcast or any command and sometimes this will leave the cli for no reason

## Screenshots

![Capture d'écran 2024-01-25 201855](https://github.com/thijsvanloef/palworld-server-docker/assets/23698300/e7209dcc-386c-441b-a6fa-5ef7a8c6d50a)

## Desktop (please complete the following information)

- OS: [pc: Windopws11, server is on my nas ds923+ with DSM 7.2.1]

## Additional context

in the screenshot i was trying to say to my friends i was gonna shutdown the server but the rcon cli disconnect all the time i don't know why

**Comment by Dashboy1998** [comment]
I've had this issue too with this container, with other palworld containers, and even using an external rcon client.
