### ISSUE TITLE
Container not entering Server-Output

### ISSUE THREAD

**Issue by LuckyTrixx** [thijsvanloef/palworld-server-docker#115]
## Describe the bug

the Container Starts, the server runs, but the Container log ends with
`[S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.`
`[S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.`
`[S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.`
`[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.`

and doesn't show any updates on Server-Events
(e. g. players joining etc)
## To Reproduce

1. Start the Container
2. Look at the Logs
## Expected behavior

Other Gameserver show events on the Game-Server, eg player joining, saving, shuting down...

## Desktop (please complete the following information)

On Ubuntu, running with the default Docker Compose File from the Repo.

## docker-compose.yml contents

1:1 the one from the Repo.

**Comment by MSpreckels** [comment]
That's something the Palworld devs have to add, there are no logs written that show these kind of events. I wish there was, too.
