### ISSUE TITLE
[Docs] Add disclaimer about Xbox and Steam Player

### ISSUE THREAD

**Issue by valentimarco** [thijsvanloef/palworld-server-docker#12]
At the moment of writing, Xbox players (so Xbox consoles and Xbox game pass pc) cannot play with steam players and therefore the custom server is available only for steam players.
I am so sad to discover this as i was making a custom server for my friends ;(

I will add a huge disclaimer in the readme and the wiki like so:

> [!IMPORTANT]
> At the moment, Xbox game pass players aren't able to join community server! You can only create private server by code

If you like the disclaimer, i can contribute with a PR!
source:
[Can you play with Game Pass on PC and Steam? ](https://steamcommunity.com/app/1623730/discussions/0/4132682727127814493/)

**Comment by thijsvanloef** [comment]
Disclaimer has been added, thank you for your input
