### ISSUE TITLE
PalWorldSettings.ini always empty

### ISSUE THREAD

**Issue by jangisaac-dev** [thijsvanloef/palworld-server-docker#126]
PalWorldSettings.ini file is created in [<mount_folder>/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini]

but is empty,

also I tried delete PalWorldSettings.ini file and restart server,

it not create .ini file

how can I find default file or create file?

**Comment by fryfrog** [comment]
You can find `DefaultPalWorldSettings.ini` in the base folder you map in for `:/palworld`.

**Comment by ivanyauhm** [comment]
![ed06a88df5de0b2ae8fbedcb936db785](https://github.com/thijsvanloef/palworld-server-docker/assets/157475532/45a2b4a9-d525-438b-a5a4-62311af8fd60)


I attempted to mapping the specified folder, but even after starting the server, no files/PalWorldSettings.ini are being generated. 
Is this a DSM issue only?

**Comment by zbellerose** [comment]
As stated above, the PalWorldSettings.ini is empty by default, you need to add content properly formatted for it to work. Here is an example of a PalWorldSettings.ini. You can find the DefaultPalWorldSettings.ini in the base folder as mentioned above

```
[/Script/Pal.PalGameWorldSettings]
OptionSettings=(AdminPassword="adminpwd",ServerDescription="",PalEggDefaultHatchingTime=5.000000)
```

**Comment by thijsvanloef** [comment]
Fixed in this PR https://github.com/thijsvanloef/palworld-server-docker/pull/145
Please make sure you are running the latest `:latest` image

**Comment by thijsvanloef** [comment]
@jangisaac-dev if you issue has been resolved, please close this issue
