### ISSUE TITLE
rcon-cli update

### ISSUE THREAD

**Issue by odakaui** [thijsvanloef/palworld-server-docker#127]
First, thank you for creating this docker container!

This issue isn't really a problem, more like something that might cause confusion for some users.

## Problem

When I run `rcon-cli` commands like `docker exec palworld-server rcon-cli [COMMAND]` I get the following response `Weird. This response is for another request. [RESPONSE]`

Functionally, the commands still work.
But, it was a definitely confusing at first.

## Solution

One possible solution might be to use [gorcon/rcon-cli](https://github.com/gorcon/rcon-cli) instead of [itzg/rcon-cli](https://github.com/itzg/rcon-cli), as it appears to work with Palworld.

Thank you for all the work you do!

**Comment by thijsvanloef** [comment]
Hi @odakaui thank you for putting this on my radar, if it works the same as the itzg one, I'll check it out now!

**Comment by odakaui** [comment]
I’ll have time to mess around with it this weekend. If I can get it to work, I’ll submit a PR.

**Comment by thijsvanloef** [comment]
@odakaui I haven't had the time for it yet, so that would be great!

**Comment by odakaui** [comment]
Ok. I created a pull request.

#148

**Comment by thijsvanloef** [comment]
Merged, closing the issue
