### ISSUE TITLE
Fix argument option name in "start.sh"

### ISSUE THREAD

**Issue by juliocsrf** [thijsvanloef/palworld-server-docker#13]
Firstly, thank you for making the repository available.

I had problems setting the PUBLIC_PORT. From what I analyzed, on line 16 of the "start.sh" file:

`STARTCOMMAND="${STARTCOMMAND} -publiport=${PUBLIC_PORT}"`

Shouldn't the argument passed be "publicport" ?

**Comment by thijsvanloef** [comment]
Good catch will be fixed ASAP

**Comment by thijsvanloef** [comment]
Issue has been fixed in 0.5.0 release
