### ISSUE TITLE
Warning message from the server

### ISSUE THREAD

**Issue by Dylseat** [thijsvanloef/palworld-server-docker#133]
## Describe the bug

I have these warning message in the screenshot and i don't know if i need to worry ?

## Screenshots

![Capture d'écran 2024-01-26 152805](https://github.com/thijsvanloef/palworld-server-docker/assets/23698300/909b99e4-178f-42fd-b82d-5b3c3bea6f9e)

## Desktop (please complete the following information)

- OS: [e.g. Windows 11, Synology ds923+ DSM 7.2]

**Comment by FurkanVG** [comment]
Your system is running with low specs which are not recommended. According to Synology Website your NAS has only 2 Cores and 4GB RAM which are not enough to run the server stable.
See here: https://github.com/thijsvanloef/palworld-server-docker#server-requirements

**Comment by Dylseat** [comment]
i have upgrade the ram to 32GB but i can't upgrade the cpu

**Comment by Dylseat** [comment]
What Nas do you recommend for hosting a server?

**Comment by thijsvanloef** [comment]
@Dylseat I recommend hosting it on a VPS or extra computer/server. I cannot test this container on synology nas, because I do not have one.

**Comment by Dylseat** [comment]
Currently we have been playing for 2-3 days with my friends, there are 5 of us and apart from small rollbacks the server is rather stable. But I'll still try your recommendation
