### ISSUE TITLE
./PalServer.sh not found

### ISSUE THREAD

**Issue by glensargent** [thijsvanloef/palworld-server-docker#139]
## Describe the bug
Starting server doesn't succeed due to 
sh: 1: ./PalServer.sh: not found

## To Reproduce

Run the docker image with documented parameters

## Expected behavior

Appropriate bash files to be present in image and server to start

## Desktop (please complete the following information)

- OS: Debian

**Comment by thijsvanloef** [comment]
Do you have some more information? 

- docker-compose.yml or docker run command
- hardware
- full log

**Comment by glensargent** [comment]
Tried both the docker compose and docker run command you provide in readme (with the volume path changed to a real folder)
On an e2-standard-4 compute engine instance on GCP running on Debian, no logs unfortunately since I've deleted the instance but image would start fine and just error on startup with that after steam client init

**Comment by thijsvanloef** [comment]
Maybe a far fetch, but could it be related to: https://github.com/thijsvanloef/palworld-server-docker/issues/93? 
I do not have a GCP account which I can test this on

**Comment by thijsvanloef** [comment]
Issue has not been active for a couple of days, reopen if necessary
