### ISSUE TITLE
Add environment variables to change User ID and Group ID

### ISSUE THREAD

**Issue by phungthomas** [thijsvanloef/palworld-server-docker#15]
Thank you for the Docker image.

Would it be possible to add environment variables to set the User ID and Group ID running the server?

**Comment by codevski** [comment]
Def needs this not able to write to host volumes that are setup for backups.

**Comment by fryfrog** [comment]
Standard `PUID=` and `PGID=` would be nice, but even docker's own `--user uid:gid` would be nice.

**Comment by thijsvanloef** [comment]
Just merged, will be on the `:latest` image on next release :)
