### ISSUE TITLE
RCON - Putty "remote side unexpectedly closed network connection

### ISSUE THREAD

**Issue by dagarnx** [thijsvanloef/palworld-server-docker#164]
## To Reproduce

1. Go to 'putty'
2. Click on under putty configuration Hostname/local ip 192.168.etc.etc port 25575, connection type ssh
3. Scroll down to 'oopen'
4. See error remote side unexpectedly closed network connection

## Desktop (please complete the following information)

- OS: [e.g. Windows 10, Ubuntu, Debian] Server side is Synology DSM 7.2, client side is windows 11
- Browser [e.g. chrome, safari] Chrome

## docker-compose.yml contents

```yaml
```

**Comment by thijsvanloef** [comment]
SSH is a different protocol and cannot be used to connect to the container, if you want to use RCON, please run the following command on the same host you run your container on:

`docker exec -it palworld-server rcon-cli`

**Comment by thijsvanloef** [comment]
SSH is a different protocol and cannot be used to connect to the container, if you want to use RCON, please run the following command on the same host you run your container on:

`docker exec -it palworld-server rcon-cli`
