### ISSUE TITLE
Secure HTTP/JSON wrapper for RCON

### ISSUE THREAD

**Issue by valamidev** [thijsvanloef/palworld-server-docker#165]
Hi, 

I've made a plugin for `palworld-server-docker` with this addition, users can protect the palworld RCON end-point with a Bearer token and access it via HTTP protocol. It also has a feature that onlinePlayers,serverTitle and serverVersion publicly accessible even if the RCON is protected.

Check it out here:
- https://github.com/valamidev/palworld-rcon-buddy

**Comment by thijsvanloef** [comment]
Sorry have not been able to pay much attention to enhancements, will add this to the official docs :)
