### ISSUE TITLE
I have a question for setting palworld server I want to change some fields on PalWorldSetting.ini in /Pal/Saved/Config/LinuxServer. But it not work. Could you guide me to setting this? Example: 

### ISSUE THREAD

**Issue by huskyloveme** [thijsvanloef/palworld-server-docker#173]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by thijsvanloef** [comment]
Hi @huskyloveme there is a section on how to change the settings in the readme: https://github.com/thijsvanloef/palworld-server-docker?tab=readme-ov-file#editing-server-settings
