### ISSUE TITLE
Server Timeout on empty server? 

### ISSUE THREAD

**Issue by JuniorGamingTime** [thijsvanloef/palworld-server-docker#178]
So the issue I'm having is that I can't reconnect to the server. When the server is started, I can connect fine the first time. The second time I connect I get a timeout error and need to restart the server to be able to connect again. 

Could this be because the server is empty?

**Comment by thijsvanloef** [comment]
Might be a duplicate of this: https://github.com/thijsvanloef/palworld-server-docker/issues/134

Are u using the recent server tab?

**Comment by JuniorGamingTime** [comment]
Oh seems like that's the issue 😅
Connecting directly with works perfectly 
Thank you so much!
