### ISSUE TITLE
World and characters disapeared after crash

### ISSUE THREAD

**Issue by Marc--** [thijsvanloef/palworld-server-docker#183]
Hi there !

We are playing for 5 days with 2 freiends on an instance of your dedicated server, and it was working well.  Thanks for your work on this dedicated server !

Sometimes, server container crashes (and seems to crash the Docker host with it !) for 5/10 mn, then restarts. Very strange behavior, but i was thinking it's linked to the memory leakage problem.

Today the container crashes again, but this time when we reconnect it reset ths world to day 0 (and asks for a new character).

Do you think it's possible to restore a previous backup ?

EDIT: I've just read the "Creating a backup" part of the doc, and of course it wasn't in place. So my backup folder is empty.

## Desktop (please complete the following information)

- OS: OpenmediaVault
- HW: Core i5 12400 / 16Gb
- Container version: 0.17

## docker-compose.yml contents

```---
version: "3.0"
services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld-server
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    network_mode: prod_bridge
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Paris
      - PORT=8211
      - PLAYERS=8
      - MULTITHREADING=true
      - ENABLE_RCON=true
      - RCON_PORT=25575
      - COMMUNITY=true
      - SERVER_PASSWORD="*********************"
      - SERVER_NAME="*************"
      - ADMIN_PASSWORD="**************************"
    volumes:
      - /srv/dev-disk-by-uuid-1da99476-7b55-497e-b2ba-7571787f2bab/docker/palworld:/palworld
  rcon:
    image: outdead/rcon:latest
    entrypoint:
      - /rcon
      - -a
      - palworld:25575
      - -p
      - *******************************
    profiles:
      - rcon
```

## Container Logs

'''01/27 21:31:03 Init: Installing breakpad exception handler for appid(steam)/version(1705108307)/tid(22)
CAppInfoCacheReadFromDiskThread took 49 milliseconds to initialize
Steam Service Error: Failed to get Steam Service Start function

01/28 00:28:30 Init: Installing breakpad exception handler for appid(steam)/version(1705108307)/tid(40)
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
Steam Service Error: Failed to get Steam Service Start function'''

**Comment by thijsvanloef** [comment]
Hi @Marc-- I'm sorry to hear that your world got corrupt. I also expect the memory leak issue being the cause of your problems. Sadly I do not think you can restore your world if you just had 1 copy of it :(

**Comment by Marc--** [comment]
Thanks for your reply. I work in IT and i know the importance of backups... but "the cobbler's children have no shoes".

I've tried some "black magic" things found on reddit but without succes. Hey it's a beta, it's a game ! I'll start a new server and add a scheduled backup and a daily reboot (hope that'll help for the memory leak ?).

Thanks again to you !
