### ISSUE TITLE
Automatic server restart?

### ISSUE THREAD

**Issue by TangJames** [thijsvanloef/palworld-server-docker#187]
Is there a way for automatic server restarts implemented?

**Comment by FurkanVG** [comment]
Just make a crontab job to restart your docker at X time. I dont think there is a reason to include this in the docker itself. For example, to restart daily at 6am:

`0 6 * * *  sudo docker restart watchtower`

**Comment by thijsvanloef** [comment]
https://github.com/thijsvanloef/palworld-server-docker/issues/37#issuecomment-1903518616 😄
