### ISSUE TITLE
RCON Broadcast command not working at all

### ISSUE THREAD

**Issue by SOSkr** [thijsvanloef/palworld-server-docker#191]
## Describe the bug

When I try to send a message, it shows me command not found!

## To Reproduce

Executing this...
`docker exec -it palworld-server rcon-cli Broadcast "Hello world"`

## Screenshots
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/1152045/776a7abf-1064-447b-8e24-fbee7ab32f37)

## Desktop (please complete the following information)

- OS: Debian

## docker-compose.yml contents

```services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-soskr-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - SERVER_NAME="PalosAmigos"
         - SERVER_DESCRIPTION="Servidor para amigos latinos"
         - PORT=8211 # Optional but recommended
         - PLAYERS=16 # Optional but recommended
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - ADMIN_PASSWORD="R3fnelU#07pbHmwR" # RCON Password
         - COMMUNITY=false # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         # - SERVER_PASSWORD="worldofpals" # Optional but recommended
         - MULTITHREADING=true
         - UPDATE_ON_BOOT=true
         - PUID=1000
         - PGID=1000
         - TZ=UTC
      volumes:
         - /home/debian/palworld-server:/palworld/
```

**Comment by Filipe-Souza** [comment]
@SOSkr Can you change the docker exec command and try this instead:

docker exec -it palworld-server /usr/bin/rcon-cli "Broadcast Hello world"

![image](https://github.com/thijsvanloef/palworld-server-docker/assets/5497281/b2dcbf7d-40c8-4476-bad1-0971f565cad1)

**Comment by SOSkr** [comment]
Worked!! thx
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/1152045/f645b1d2-3cb1-45d1-808f-21b1715f922f)
