### ISSUE TITLE
I seem to have a problem with the settings configuration

### ISSUE THREAD

**Issue by dexterIshere** [thijsvanloef/palworld-server-docker#213]
## Server runs without the setings configured in PalWorldSettings.ini

I'm not the player in this story, but i hosted a server using your compose file in a dedicated serv for my homies.
At the begining i only customised the parameters in the PalWorldSettings.ini located inside blablabla/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini. wich was like that :

```ini
[/Script/Pal.PalGameWorldSettings]
OptionSettings=(Difficulty=Difficult,DayTimeSpeedRate=1.000000,NightTimeSpeedRate=1.000000,ExpRate=1.000000,PalCaptureRate=1.000000,PalSpawnNumRate=1.000000,PalDamageRateAttack=1.000000,PalDamageRateDefense=1.000000,PlayerDamageRateAttack=1.000000,PlayerDamageRateDefense=1.000000,PlayerStomachDecreaceRate=1.000000,PlayerStaminaDecreaceRate=1.000000,PlayerAutoHPRegeneRate=1.000000,PlayerAutoHpRegeneRateInSleep=1.000000,PalStomachDecreaceRate=1.000000,PalStaminaDecreaceRate=1.000000,PalAutoHPRegeneRate=1.000000,PalAutoHpRegeneRateInSleep=1.000000,BuildObjectDamageRate=1.000000,BuildObjectDeteriorationDamageRate=1.000000,CollectionDropRate=1.000000,CollectionObjectHpRate=1.000000,CollectionObjectRespawnSpeedRate=1.000000,EnemyDropItemRate=1.000000,DeathPenalty=All,bEnablePlayerToPlayerDamage=False,bEnableFriendlyFire=False,bEnableInvaderEnemy=True,bActiveUNKO=False,bEnableAimAssistPad=True,bEnableAimAssistKeyboard=False,DropItemMaxNum=3000,DropItemMaxNum_UNKO=100,BaseCampMaxNum=128,BaseCampWorkerMaxNum=15,DropItemAliveMaxHours=1.000000,bAutoResetGuildNoOnlinePlayers=False,AutoResetGuildTimeNoOnlinePlayers=72.00000,GuildPlayerMaxNum=20,PalEggDefaultHatchingTime=2.00000,WorkSpeedRate=1.000000,bIsMultiplay=False,bIsPvP=True,bCanPickupOtherGuildDeathPenaltyDrop=False,bEnableNonLoginPenalty=True,bEnableFastTravel=True,bIsStartLocationSelectByMap=True,bExistPlayerAfterLogout=False,bEnableDefenseOtherGuildPlayer=False,CoopPlayerMaxNum=4,ServerPlayerMaxNum=16,ServerName="Default Palworld Server",ServerDescription="",AdminPassword="",ServerPassword="",PublicPort=8211,PublicIP="",RCONEnabled=true,RCONPort=25575,Region="",bUseAuth=True,BanListURL="https://api.palworldgame.com/api/banlist.txt")
```

But they say that the game was not in Difficult. So i decided to move with the .env file. and the PalWorldSettings.ini file turn into this :
```ini
; This configuration file is a sample of the default server settings.
; Changes to this file will NOT be reflected on the server.
; To change the server settings, modify Pal/Saved/Config/LinuxServer/PalWorldSettings.ini.
[/Script/Pal.PalGameWorldSettings]
OptionSettings=(Difficulty=Difficult,DayTimeSpeedRate=1.000000,NightTimeSpeedRate=1.000000,ExpRate=1.000000,PalCaptureRate=1.000000,PalSpawnNumRate=1.000000,PalDamageRateAttack=1.000000,PalDamageRateDefense=1.000000,PlayerDamageRateAttack=1.000000,PlayerDamageRateDefense=1.000000,PlayerStomachDecreaceRate=1.000000,PlayerStaminaDecreaceRate=1.000000,PlayerAutoHPRegeneRate=1.000000,PlayerAutoHpRegeneRateInSleep=1.000000,PalStomachDecreaceRate=1.000000,PalStaminaDecreaceRate=1.000000,PalAutoHPRegeneRate=1.000000,PalAutoHpRegeneRateInSleep=1.000000,BuildObjectDamageRate=1.000000,BuildObjectDeteriorationDamageRate=1.000000,CollectionDropRate=1.000000,CollectionObjectHpRate=1.000000,CollectionObjectRespawnSpeedRate=1.000000,EnemyDropItemRate=1.000000,DeathPenalty=All,bEnablePlayerToPlayerDamage=False,bEnableFriendlyFire=False,bEnableInvaderEnemy=True,bActiveUNKO=False,bEnableAimAssistPad=True,bEnableAimAssistKeyboard=False,DropItemMaxNum=3000,DropItemMaxNum_UNKO=100,BaseCampMaxNum=128,BaseCampWorkerMaxNum=15,DropItemAliveMaxHours=1.000000,bAutoResetGuildNoOnlinePlayers=False,AutoResetGuildTimeNoOnlinePlayers=72.00000,GuildPlayerMaxNum=20,PalEggDefaultHatchingTime=2.00000,WorkSpeedRate=1.000000,bIsMultiplay=False,bIsPvP=True,bCanPickupOtherGuildDeathPenaltyDrop=False,bEnableNonLoginPenalty=True,bEnableFastTravel=True,bIsStartLocationSelectByMap=True,bExistPlayerAfterLogout=False,bEnableDefenseOtherGuildPlayer=False,CoopPlayerMaxNum=4,ServerPlayerMaxNum=16,ServerName="Default Palworld Server",ServerDescription="",AdminPassword="",ServerPassword="",PublicPort=8211,PublicIP="",RCONEnabled=true,RCONPort=25575,Region="",bUseAuth=True,BanListURL="https://api.palworldgame.com/api/banlist.txt")
```
And same result not even the Dificulty mode changed. BUUUUUUUUUT, in the .env file i changed the servname and password + description and this changes worked because they were able to connect. So why game settings wont work.

THX

**Comment by chickiyeah** [comment]
for now this is yesterday image 
image id : sha256:6f168a13792cd29c0ab1a103d706eeb280b4a847dc796baa57be5a6be0523280
change use image to this

https://drive.google.com/file/d/19XNxFsn__buVYu-sP48VkrF45W_O80zo/view?usp=sharing

**Comment by dexterIshere** [comment]
THX. i'll try and come back to you

**Comment by dexterIshere** [comment]
> for now this is yesterday image image id : sha256:6f168a13792cd29c0ab1a103d706eeb280b4a847dc796baa57be5a6be0523280 change use image to this
> 
> https://drive.google.com/file/d/19XNxFsn__buVYu-sP48VkrF45W_O80zo/view?usp=sharing

what am'i suposed to do exactly ?

**Comment by bbung224** [comment]
As far as I know, the Difficulty setting is not valid on dedicated servers. You will have to adjust the detailed difficulty.

**Comment by chickiyeah** [comment]
I understood that the Palworldsetting was not completely working, so I told you how, but I think I got it wrong

**Comment by dexterIshere** [comment]
sry but what do you mi by "adjust the detailed difficulty."

**Comment by dexterIshere** [comment]
> I understood that the Palworldsetting was not completely working, so I told you how, but I think I got it wrong

ha ok ok

**Comment by bbung224** [comment]
ExpRate, PalCaptureRate, CollectionDropRate, etc..
You might want to check out the following link.
https://www.bisecthosting.com/clients/index.php?rp=/knowledgebase/968/How-to-change-the-difficulty-on-a-Palworld-server.html

Also, your dedicated server should be on "Hard" difficulty, but if your players say your server is easy, you should probably make it harder.

**Comment by bbung224** [comment]
Sorry, I don't know about the PVP settings. I haven't tested it.

**Comment by dexterIshere** [comment]
np, but by chance, do you know why the Difficulty field may cause issues.

**Comment by bbung224** [comment]
I have no clue

**Comment by dexterIshere** [comment]
> I have no clue

hmmm, it seem that this is a kind of Preset that if you change it you'd better not to change anything

**Comment by thijsvanloef** [comment]
Problem should be resolved in update 0.19.1 thanks to `beomseok-park`, please pull the latest image and check if your issue has been resolved.

**Comment by thijsvanloef** [comment]
If you are still having trouble after updating, please remove your PalWorldSettings.ini and restart your container.

**Comment by GuillaumeBarreau** [comment]
I just got back, sorry I was away on a business trip for a week. Thank you for continuing my PR :)

Regarding the Setting file, it seems that when we start the starts.sh script, it works correctly and rewrites the Pal configuration file. However, currently, there's an invisible character being added with PalCaptureRate=1.000000e, making the file unreadable for the server and preventing the new server configuration from working.

I deleted the lines that modify EXP_RATE and PalCaptureRate in the starts.sh file, and since then, everything has been working again.

**Comment by GuillaumeBarreau** [comment]
I am writing a method that is a bit more readable in an attempt to simplify and make the writing of this file clearer, as it's a bit complicated to maintain at the moment."

<img width="991" alt="Screenshot 2024-01-30 at 22 50 59" src="https://github.com/thijsvanloef/palworld-server-docker/assets/43338251/707a5216-6708-4e47-a593-c2db4b9b135a">

**Comment by thijsvanloef** [comment]
Closing this issue to merge all related issues into one: https://github.com/thijsvanloef/palworld-server-docker/issues/239
