### ISSUE TITLE
When you execute the command `docker restart palworld-server`, and you find that your server configuration (`PalWorldSettings.ini`) always resets

### ISSUE THREAD

**Issue by anduinnn** [thijsvanloef/palworld-server-docker#217]
1. Edit `/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini`
2. `docker restart palworld-server`
3. ![image](https://github.com/thijsvanloef/palworld-server-docker/assets/68073009/dde26aae-f45d-4263-82b8-2a52b7328325)
   "You will see that the modification times for these files are all identical, which suggests that my configuration file has been overwritten."

**Comment by anduinnn** [comment]
this is my configuration
`[/Script/Pal.PalGameWorldSettings]
OptionSettings=(Difficulty=None,DayTimeSpeedRate=1.000000,NightTimeSpeedRate=1.000000,ExpRate=2.000000,PalCaptureRate=1.000000,PalSpawnNumRate=1.000000,PalDamageRateAttack=1.000000,PalDamageRateDefense=1.000000,PlayerDamageRateAttack=1.000000,PlayerDamageRateDefense=1.000000,PlayerStomachDecreaceRate=1.000000,PlayerStaminaDecreaceRate=1.000000,PlayerAutoHPRegeneRate=1.000000,PlayerAutoHpRegeneRateInSleep=1.000000,PalStomachDecreaceRate=1.000000,PalStaminaDecreaceRate=1.000000,PalAutoHPRegeneRate=1.000000,PalAutoHpRegeneRateInSleep=1.000000,BuildObjectDamageRate=1.000000,BuildObjectDeteriorationDamageRate=1.000000,CollectionDropRate=2.000000,CollectionObjectHpRate=1.000000,CollectionObjectRespawnSpeedRate=1.000000,EnemyDropItemRate=2.000000,DeathPenalty=None,bEnablePlayerToPlayerDamage=False,bEnableFriendlyFire=False,bEnableInvaderEnemy=True,bActiveUNKO=False,bEnableAimAssistPad=True,bEnableAimAssistKeyboard=False,DropItemMaxNum=3000,DropItemMaxNum_UNKO=100,BaseCampMaxNum=128,BaseCampWorkerMaxNum=15,DropItemAliveMaxHours=1.000000,bAutoResetGuildNoOnlinePlayers=False,AutoResetGuildTimeNoOnlinePlayers=72.000000,GuildPlayerMaxNum=20,PalEggDefaultHatchingTime=5.000000,WorkSpeedRate=1.000000,bIsMultiplay=False,bIsPvP=False,bCanPickupOtherGuildDeathPenaltyDrop=False,bEnableNonLoginPenalty=True,bEnableFastTravel=True,bIsStartLocationSelectByMap=True,bExistPlayerAfterLogout=False,bEnableDefenseOtherGuildPlayer=False,CoopPlayerMaxNum=4,ServerPlayerMaxNum=32,ServerName="[ohiyou]2X掉落2X经验5H孵化死亡不掉落",ServerDescription="和谐游戏,开心玩耍,服务器禁止捕捉塔主",AdminPassword="4144home",ServerPassword="5216",PublicPort=8211,PublicIP="",RCONEnabled=False,RCONPort=25575,Region="",bUseAuth=True,BanListURL="https://api.palworldgame.com/api/banlist.txt")`

**Comment by bbung224** [comment]
During the restart process, any modifications you made during the stop will be restored. Stop, modify, and start.

**Comment by Dashboy1998** [comment]
This is a known issue with the game. While it's mentioned in [README](https://github.com/thijsvanloef/palworld-server-docker?tab=readme-ov-file#manually) for `PalWorldSettings.ini` it would appear to apply to all of the configs.
