### ISSUE TITLE
REGION ENV variable is missing from both Dockerfile and helm chart

### ISSUE THREAD

**Issue by jryanearl** [thijsvanloef/palworld-server-docker#227]
## Describe the bug

REGION is missing from the Dockerfile env variables, this leaves region="" in the final config file.  

## To Reproduce

Use 0.18.0 (latest wasn't working for me, "" problems in config variables) to start a Palworld instance.  I'm using a docker GUI which brings up all the ENV variables.  REGION is not there.

## Steps to reproduce

I'm using Container Manager on DSM 7.2.1 (Synology) it's easy to see the REGION ENV variable is missing there.  Looking at source code, can see region is missing in both the Dockerfile and the helm chart.

## Expected behavior

Should be able to set REGION info for Palword server.

## Screenshots

<img width="1428" alt="missing_region_env" src="https://github.com/thijsvanloef/palworld-server-docker/assets/6120002/78c6b481-9f1d-4c6f-b270-fb7cf60dda26">

## Desktop (please complete the following information)
~$ docker --version
Docker version 20.10.23, build 876964a

**Comment by thijsvanloef** [comment]
The REGION env var is empty by default, have you explicitly set the REGION env?

**Comment by jryanearl** [comment]
I did explicitly set it and it worked, so maybe working as intended.
