### ISSUE TITLE
Wiki Update

### ISSUE THREAD

**Issue by Dashboy1998** [thijsvanloef/palworld-server-docker#237]
## Describe the bug

In the wiki under [Stopping the server](https://github.com/thijsvanloef/palworld-server-docker/wiki#stopping-the-server) it says to use `docker compose down` but that [stops the container and remove containers & networks.](https://docs.docker.com/engine/reference/commandline/compose_down/)

It should use `docker compose stop` which [stops the container.](https://docs.docker.com/engine/reference/commandline/compose_stop/)

**Comment by thijsvanloef** [comment]
Done!
