### ISSUE TITLE
ENV variable issues after update 0.18.0

### ISSUE THREAD

**Issue by thijsvanloef** [thijsvanloef/palworld-server-docker#239]
Hi,

Due to a faulty PR the settings of some folks got messed up resulting in only the ./PalServer.sh parameters working to change settings.

This issue should be resolved in 0.19.1. However it does require that you do the following:

- `docker compose down --rmi all`
- Remove `palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini`
- Change your docker compose to match [the latest template](https://github.com/thijsvanloef/palworld-server-docker/blob/main/docker-compose.yml)
- `docker compose up -d`

Thank you for your patience, a PR has been opened to hopefully fix all environment errors https://github.com/thijsvanloef/palworld-server-docker/pull/207.

**Comment by dexterIshere** [comment]
thx !

**Comment by PulsarFTW** [comment]
I've had time to do some testing now, and I can confirm that after deleting the existing config file, it works! 

Thanks!

**Comment by Marc--** [comment]
Thanks for the fix, i confirm it's working fine with 0.19.1.

**Comment by Lizardbutt** [comment]
There's a better way to do this. Throw your `default.env` variables into the docker compose file for the value changes needed.  

1. Set wanted value changes from `default.env` into your `docker-compose.yml` file under `environment:`
1. `docker compose down --rmi all`
1. `rm palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini`
1. `docker compose up -d`

I've confirmed three times over this works. Editing the .ini does not.


`services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      stop_grace_period: 30s # Set to however long you are willing to wait for the container to gracefully stop
      ports:
        - 8211:8211/udp
        - 27015:27015/udp # Required if you want your server to show up in the community servers tab
      environment:
         - PUID=1000
         - PGID=1000
         - PORT=8211 # Optional but recommended
         - PLAYERS=16 # Optional but recommended
         - SERVER_PASSWORD= # Optional but recommended
         - MULTITHREADING=true
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - TZ=UTC
         - DIFFICULTY=Normal # These are the three value changes I made. 
         - PAL_EGG_DEFAULT_HATCHING_TIME=5.000000 # and this one
         - DEATH_PENALTY=Item # and this one.
         - ADMIN_PASSWORD=
         - COMMUNITY=false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         - SERVER_NAME=
         - SERVER_DESCRIPTION=
      volumes:
         - ./palworld:/palworld/`
