### ISSUE TITLE
Palworld save corruption after guild collectively catch/sell/butcher/drop/etc 7000 pals

### ISSUE THREAD

**Issue by v4de** [thijsvanloef/palworld-server-docker#245]
**Is your feature request related to a problem? Please describe.**
Some Palworld server saves are being corrupted or the servers will constantly crash on start.

The current workaround is run fix_save.py using the code from this [repo](https://github.com/HyperBCS/palworld-save-tools/blob/main/fix_save.py) thanks to user [HyperBCS](https://github.com/HyperBCS)

The instructions were posted on [reddit](https://www.reddit.com/r/Palworld/comments/1aeffoq/fix_for_server_pal_catch_limit_bug/)
>Simply drag Level.sav into fix_world.cmd or run the python script fix_save.py with the filename as the argument. If no --output argument was given, the file will be saved into a folder named "fixed". This script is largely untested so please make a backup and report any bugs. 

**Describe the solution you'd like**
I propose automating this to run on container start as a current workaround until palworld resolves the bug. As this is largely untested it should be optional and save backups should be automatically inferred or warning in documentation that when enabling it is highly recommend to also automate backups as it may corrupt the save.

**Describe alternatives you've considered**
No alternatives currently known.

**Additional context**
No additional context

**Comment by xHyperElectric** [comment]
This was supposedly fixed in Palworld patch 0.1.4.0
"・Implemented the first fix for an issue where the game would always crash and save data would be corrupted when the guild's total number of pals captured reached around 7000.
*The game no longer crashes even if the total number of captured objects exceeds 7000."

**Comment by v4de** [comment]
You are right, it was just fixed with the most recent patch that came out today. The save fix is only needed for servers that have had the issue happen to them as the patch will not repair already corrupted saves. Thank you PocketPair!
