### ISSUE TITLE
Unable to start after modifying server settings through docker environment variables

### ISSUE THREAD

**Issue by flyingnight** [thijsvanloef/palworld-server-docker#249]
您好，我通过docker的环境变量修改服务器设置后（不是修改PalWorldSettings.ini文件），服务器无法启动了，日志报告如下，过一段时间后会自动退出重新出现这个日志报告，不断循环

![image](https://github.com/thijsvanloef/palworld-server-docker/assets/63300561/cbfcdfe0-d2af-49fb-b114-ae3df2686d29)

**Comment by Cp0204** [comment]
国际项目 提问题建议至少翻译成人家看得懂语言，以示尊重。

**Comment by win5923** [comment]
Can you provide the commands you executed?

**Comment by flyingnight** [comment]
`docker run -d \
    --name palworld-server \
    -p 8211:8211/udp \
    -p 27015:27015/udp \
    -v ./<palworld-folder>:/palworld/ \
    -e PUID=100 \
    -e PGID=100 \
    -e PORT=8211 \
    -e PLAYERS=16 \
    -e MULTITHREADING=true \
    -e RCON_ENABLED=true \
    -e RCON_PORT=25575 \
    -e TZ=Asia/Shanghai \
    -e ADMIN_PASSWORD="adminPasswordHere" \
    -e SERVER_PASSWORD="worldofpals" \
    -e COMMUNITY=false \
    -e SERVER_NAME="World of Pals" \
    -e BACKUP_ENABLED=true \
    -e BACKUP_CRON_EXPRESSION=0 2 * * *\
    --restart unless-stopped \
    thijsvanloef/palworld-server-docker:latest
`
I deployed the above code, and when it was just deployed, the server was available and I could enter the server. But when I modified the parameters in the PalWorldSettings.ini file, the docker couldn't start. In order to prevent the code in the file from causing the problem, I manually only modified the numbers, but still couldn't enter.

**Comment by win5923** [comment]
If directly modify the environment variables of the docker run command, will it still result in an error?

Alternatively, you may consider using docker compose.

**Comment by win5923** [comment]
I don't think directly modifying the PalWorldSettings.ini file is a good approach.
it's preferable to recreate the container using either docker run or docker-compose up.

**Comment by thijsvanloef** [comment]
@flyingnight Please make sure you've followed these steps:
`docker compose down --rmi all`

`Remove palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini`


`docker compose up -d`

**Comment by Dissssy** [comment]
As modifying the ini isnt recommended, Is there possibly a way to force specifically the config to stay inside the container that way when you recreate with docker its regenerated? changing the env works but it should actually reflect when you recreate, imo

**Comment by win5923** [comment]
> As modifying the ini isnt recommended, Is there possibly a way to force specifically the config to stay inside the container that way when you recreate with docker its regenerated? changing the env works but it should actually reflect when you recreate, imo

In the context of Docker Compose, when modifying the contents of the `env_file`, upon starting the container, the `start.sh` script will copy each parameter from the `env` file to `PalWorldSettings.ini` during server initialization.

Therefore, directly modifying the content of the `ini` file doesn't take effect when starting through Docker Compose.

**Comment by thijsvanloef** [comment]
@flyingnight if you still have these issues please reopen this issue
