### ISSUE TITLE
rcon-cli does not support utf-8 messages

### ISSUE THREAD

**Issue by mingyc** [thijsvanloef/palworld-server-docker#253]
## Describe the bug

It is expected that utf-8 message can also be broadcasted using `rcon-cli`.

## To Reproduce

```
docker exec -it palworld-server rcon-cli "Broadcast 測試"
```

## Expected behavior

The string "測試" should be the broadcast result in the game.

## Screenshots

Some random string appears

![1](https://github.com/thijsvanloef/palworld-server-docker/assets/504463/004a361a-9f84-475a-b8b8-7b1403ac29b1)

## Desktop (please complete the following information)

- OS: Debian 12
## docker-compose.yml contents

not relevant

**Comment by PaulusParssinen** [comment]
[Source RCON is ASCII-only protocol](https://developer.valvesoftware.com/wiki/Source_RCON_Protocol), unless the implementation has been modified by the game developers. I don't think we can do much here(?)

**Comment by thijsvanloef** [comment]
The rcon-cli package is not maintained by me, please open an issue on https://github.com/gorcon/rcon-cli
