### ISSUE TITLE
Server lag after migrating my save

### ISSUE THREAD

**Issue by funkymango221** [thijsvanloef/palworld-server-docker#256]
On a fresh world, the server was running at 40 ping and 60 server fps. I then used these steps to migrate my world save:
1. Download Pal/Saved/SaveGames from windows server you are trying to transfer over

Make sure your Linux Palword server is a clean install and not something you experimented on

2. Start Linux server and let boot to generate files.

3. Stop Linux Server (Do not start the server again until the end)

4. Delete the Pal/Saved/SaveGames from the Linux server, and replace it with the one from Windows. It should now look like Pal/Saved/SaveGames/0/(bunch of random numbers)

5. In "/Pal/Saved/Config/LinuxServer" edit "GameUserSettings.ini" and change "DedicatedServerName" to the random numbers in your "Pal/Saved/SaveGames/0/" folder (example - DedicatedServerName=77ESD4

After transferring my old save from windows server, I am now getting over 100 ping and 10-20 server fps and I received this message:

palworld-server  | Setting breakpad minidump AppID = 2394010
palworld-server  | [S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
palworld-server  | [S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
palworld-server  | [S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
palworld-server  | [S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
palworld-server  | LogPakFile: Display: Found Pak file ../../../Engine/Programs/CrashReportClient/Content/Paks/CrashReportClient.pak attempting to mount.
palworld-server  | LogPakFile: Display: Mounting pak file ../../../Engine/Programs/CrashReportClient/Content/Paks/CrashReportClient.pak.
palworld-server  | LogPakFile: Display: Mounted Pak file '../../../Engine/Programs/CrashReportClient/Content/Paks/CrashReportClient.pak', mount point: '../../../Engine/'
palworld-server  | LogICUInternationalization: ICU TimeZone Detection - Raw Offset: +0:00, Platform Override: ''
palworld-server  | LogInit: Build: ++UE5+Release-5.1-CL-0
palworld-server  | LogInit: Engine Version: 5.1.1-0+++UE5+Release-5.1
palworld-server  | LogInit: Compatible Engine Version: 5.1.0-0+++UE5+Release-5.1
palworld-server  | LogInit: Net CL: 0
palworld-server  | LogInit: OS: Ubuntu 22.04.3 LTS (5.15.0), CPU: FEX-2312.1                      Neoverse N1, GPU: UnknownVendor PCI-id: 108e-0010
palworld-server  | LogInit: Compiled (64-bit): Dec 31 2023 20:12:22
palworld-server  | LogInit: Compiled with Clang: 13.0.1 (https://github.com/llvm/llvm-project 75e33f71c2dae584b13a7d1186ae0a038ba98838)
palworld-server  | LogInit: Build Configuration: Shipping
palworld-server  | LogInit: Branch Name: ++UE5+Release-5.1
palworld-server  | LogInit: Command Line:  -Abslog="/palworld/Pal/Saved/Logs/Pal-CRC.log" -Unattended -ImplicitSend "/palworld/Pal/Saved/Crashes/crashinfo-Pal-pid-94-E1D47FC58B6541A68A5904B97138F6E4/" -unattended
palworld-server  | LogInit: Base Directory: /palworld/Engine/Binaries/Linux/
palworld-server  | LogInit: Allocator: Mimalloc
palworld-server  | LogInit: Installed Engine Build: 1
palworld-server  | LogInit: Presizing for max 100000 objects, including 0 objects not considered by GC, pre-allocating 0 bytes for permanent pool.
palworld-server  | LogInit: Object subsystem initialized
palworld-server  | [2024.02.01-19.38.25:449][  0]LogConfig: Applying CVar settings from Section [ConsoleVariables] File [Engine]
palworld-server  | [2024.02.01-19.38.25:452][  0]LogInit: Unix hardware info:
palworld-server  | [2024.02.01-19.38.25:453][  0]LogInit:  - we are the first instance of this executable
palworld-server  | [2024.02.01-19.38.25:453][  0]LogInit:  - this process' id (pid) is 142, parent process' id (ppid) is 94
palworld-server  | [2024.02.01-19.38.25:453][  0]LogInit:  - we are not running under debugger
palworld-server  | [2024.02.01-19.38.25:454][  0]LogInit:  - machine network name is '22b56349de2a'
palworld-server  | [2024.02.01-19.38.25:454][  0]LogInit:  - user name is 'steam' (steam)
palworld-server  | [2024.02.01-19.38.25:454][  0]LogInit:  - we're logged in locally
palworld-server  | [2024.02.01-19.38.25:454][  0]LogInit:  - we're running with rendering
palworld-server  | [2024.02.01-19.38.25:454][  0]LogInit:  - CPU: GenuineIntel 'FEX-2312.1                      Neoverse N1' (signature: 0x10670)
palworld-server  | [2024.02.01-19.38.25:454][  0]LogInit:  - Number of physical cores available for the process: 4
palworld-server  | [2024.02.01-19.38.25:455][  0]LogInit:  - Number of logical cores available for the process: 4
palworld-server  | [2024.02.01-19.38.25:455][  0]LogInit:  - Cache line size: 64
palworld-server  | [2024.02.01-19.38.25:455][  0]LogInit:  - GPU Brand Info: UnknownVendor PCI-id: 108e-0010
palworld-server  | [2024.02.01-19.38.25:455][  0]LogInit:  - Memory allocator used: Mimalloc
palworld-server  | [2024.02.01-19.38.25:455][  0]LogInit:  - This binary is optimized with LTO: no, PGO: no, instrumented for PGO data collection: no
palworld-server  | [2024.02.01-19.38.25:455][  0]LogInit:  - This is an internal build.
palworld-server  | [2024.02.01-19.38.25:456][  0]LogCore: Skipped benchmarking clocks because the engine is running in a standalone program mode - CLOCK_MONOTONIC will be used.
palworld-server  | [2024.02.01-19.38.25:456][  0]LogInit: Unix-specific commandline switches:
palworld-server  | [2024.02.01-19.38.25:456][  0]LogInit:  -ansimalloc - use malloc()/free() from libc (useful for tools like valgrind and electric fence)
palworld-server  | [2024.02.01-19.38.25:456][  0]LogInit:  -jemalloc - use jemalloc for all memory allocation
palworld-server  | [2024.02.01-19.38.25:456][  0]LogInit:  -binnedmalloc - use binned malloc  for all memory allocation
palworld-server  | [2024.02.01-19.38.25:457][  0]LogInit:  -filemapcachesize=NUMBER - set the size for case-sensitive file mapping cache
palworld-server  | [2024.02.01-19.38.25:457][  0]LogInit:  -useksm - uses kernel same-page mapping (KSM) for mapped memory (OFF)
palworld-server  | [2024.02.01-19.38.25:457][  0]LogInit:  -ksmmergeall - marks all mmap'd memory pages suitable for KSM (OFF)
palworld-server  | [2024.02.01-19.38.25:457][  0]LogInit:  -preloadmodulesymbols - Loads the main module symbols file into memory (OFF)
palworld-server  | [2024.02.01-19.38.25:457][  0]LogInit:  -sigdfl=SIGNAL - Allows a specific signal to be set to its default handler rather then ignoring the signal
palworld-server  | [2024.02.01-19.38.25:458][  0]LogInit:  -crashhandlerstacksize - Allows setting crash handler stack sizes (204800)
palworld-server  | [2024.02.01-19.38.25:458][  0]LogInit:  -noexclusivelockonwrite - disables marking files created by the engine as exclusive locked while the engine has them opened
palworld-server  | [2024.02.01-19.38.25:458][  0]LogInit:  -httpproxy=ADDRESS:PORT - redirects HTTP requests to a proxy (only supported if compiled with libcurl)
palworld-server  | [2024.02.01-19.38.25:458][  0]LogInit:  -reuseconn - allow libcurl to reuse HTTP connections (only matters if compiled with libcurl)
palworld-server  | [2024.02.01-19.38.25:458][  0]LogInit:  -virtmemkb=NUMBER - sets process virtual memory (address space) limit (overrides VirtualMemoryLimitInKB value from .ini)
palworld-server  | [2024.02.01-19.38.25:458][  0]LogInit:  - Physical RAM available (not considering process quota): 24 GB (23987 MB, 24563588 KB, 25153114112 bytes)
palworld-server  | [2024.02.01-19.38.25:462][  0]LogInit:  - VirtualMemoryAllocator pools will grow at scale 1.4
palworld-server  | [2024.02.01-19.38.25:462][  0]LogInit:  - MemoryRangeDecommit() will be a no-op (re-run with -vmapoolevict to change)
palworld-server  | [2024.02.01-19.38.25:462][  0]LogInit:  - PageSize 4096
palworld-server  | [2024.02.01-19.38.25:463][  0]LogInit:  - BinnedPageSize 65536
palworld-server  | [2024.02.01-19.38.25:596][  0]LogUObjectArray: 419 objects as part of root set at end of initial load.
palworld-server  | [2024.02.01-19.38.25:596][  0]LogUObjectAllocator: 89064 out of 0 bytes used by permanent object pool.
palworld-server  | [2024.02.01-19.38.25:596][  0]LogUObjectArray: CloseDisregardForGC: 0/0 objects in disregard for GC pool
palworld-server  | [2024.02.01-19.38.25:601][  0]LogPaths: Warning: No paths for game localization data were specifed in the game configuration.
palworld-server  | [2024.02.01-19.38.25:602][  0]LogInit: Using OS detected language (en-US-POSIX).
palworld-server  | [2024.02.01-19.38.25:602][  0]LogInit: Using OS detected locale (en-US-POSIX).
palworld-server  | [2024.02.01-19.38.25:603][  0]LogInit: Warning: No paths for engine localization data were specifed in the engine configuration.
palworld-server  | [2024.02.01-19.38.25:608][  0]LogTextLocalizationManager: No localization for 'en-US-POSIX' exists, so 'en' will be used for the language.
palworld-server  | [2024.02.01-19.38.25:608][  0]LogTextLocalizationManager: No localization for 'en-US-POSIX' exists, so 'en' will be used for the locale.
palworld-server  | [2024.02.01-19.38.25:615][  0]LogInit: Using OS detected language (en-US-POSIX).
palworld-server  | [2024.02.01-19.38.25:615][  0]LogInit: Using OS detected locale (en-US-POSIX).
palworld-server  | [2024.02.01-19.38.25:615][  0]LogTextLocalizationManager: No localization for 'en-US-POSIX' exists, so 'en' will be used for the language.
palworld-server  | [2024.02.01-19.38.25:615][  0]LogTextLocalizationManager: No localization for 'en-US-POSIX' exists, so 'en' will be used for the locale.
palworld-server  | [2024.02.01-19.38.25:652][  0]LogPackageLocalizationCache: Processed 2 localized package path(s) for 1 prioritized culture(s) in 0.011120 seconds
palworld-server  | [2024.02.01-19.38.25:656][  0]CrashReportCoreLog: CrashReportClientVersion=1.0
palworld-server  | [2024.02.01-19.38.25:657][  0]CrashReportCoreLog: CrashReportReceiver disabled
palworld-server  | [2024.02.01-19.38.25:657][  0]CrashReportCoreLog: DataRouterUrl: https://o1291919.ingest.sentry.io/api/6513339/unreal/4a1a3921f51f4975b4cf8dd19022cb20/
palworld-server  | [2024.02.01-19.38.25:696][  0]CrashReportCoreLog: Initial state = Unknown UploadState value
palworld-server  | [2024.02.01-19.38.25:697][  0]CrashReportCoreLog: Initial state = Unknown UploadState value
palworld-server  | [2024.02.01-19.38.25:768][  0]LogCrashDebugHelper: DepotName: //UE5/Release-5.1
palworld-server  | [2024.02.01-19.38.25:768][  0]LogCrashDebugHelper: BuiltFromCL: 0
palworld-server  | [2024.02.01-19.38.25:768][  0]LogCrashDebugHelper: EngineVersion: 5.1.1-0+++UE5+Release-5.1
palworld-server  | [2024.02.01-19.38.25:768][  0]LogCrashDebugHelper: BuildVersion: ++UE5+Release-5.1-CL-0
palworld-server  | [2024.02.01-19.38.26:774][  0]CrashReportCoreLog: Got 3 pending files to upload from 'crashinfo-Pal-pid-94-E1D47FC58B6541A68A5904B97138F6E4'
palworld-server  | [2024.02.01-19.38.26:774][  0]CrashReportCoreLog: State change from Ready to SendingFiles
palworld-server  | [2024.02.01-19.38.26:774][  0]CrashReportCoreLog: CompressAndSendData have 3 pending files
palworld-server  | [2024.02.01-19.38.26:776][  0]CrashReportCoreLog: CompressAndSendData compressing 321 bytes ('/palworld/Pal/Saved/Crashes/crashinfo-Pal-pid-94-E1D47FC58B6541A68A5904B97138F6E4/Diagnostics.txt')
palworld-server  | [2024.02.01-19.38.26:777][  0]CrashReportCoreLog: CompressAndSendData compressing 152 bytes ('/palworld/Pal/Saved/Crashes/crashinfo-Pal-pid-94-E1D47FC58B6541A68A5904B97138F6E4/CrashReportClient.ini')
palworld-server  | [2024.02.01-19.38.26:777][  0]CrashReportCoreLog: CompressAndSendData compressing 6350 bytes ('/palworld/Pal/Saved/Crashes/crashinfo-Pal-pid-94-E1D47FC58B6541A68A5904B97138F6E4/CrashContext.runtime-xml')
palworld-server  | [2024.02.01-19.38.26:987][  0]LogInit: Using libcurl 7.83.1
palworld-server  | [2024.02.01-19.38.26:987][  0]LogInit:  - built for Linux
palworld-server  | [2024.02.01-19.38.26:988][  0]LogInit:  - supports SSL with OpenSSL/1.1.1n
palworld-server  | [2024.02.01-19.38.26:988][  0]LogInit:  - supports HTTP deflate (compression) using libz 1.2.12
palworld-server  | [2024.02.01-19.38.26:988][  0]LogInit:  - other features:
palworld-server  | [2024.02.01-19.38.26:988][  0]LogInit:      CURL_VERSION_SSL
palworld-server  | [2024.02.01-19.38.26:988][  0]LogInit:      CURL_VERSION_LIBZ
palworld-server  | [2024.02.01-19.38.26:988][  0]LogInit:      CURL_VERSION_IPV6
palworld-server  | [2024.02.01-19.38.26:988][  0]LogInit:      CURL_VERSION_ASYNCHDNS
palworld-server  | [2024.02.01-19.38.26:989][  0]LogInit:      CURL_VERSION_LARGEFILE
palworld-server  | [2024.02.01-19.38.26:994][  0]LogInit:  CurlRequestOptions (configurable via config and command line):
palworld-server  | [2024.02.01-19.38.26:994][  0]LogInit:  - bVerifyPeer = false  - Libcurl will NOT verify peer certificate
palworld-server  | [2024.02.01-19.38.26:994][  0]LogInit:  - bUseHttpProxy = false  - Libcurl will NOT use HTTP proxy
palworld-server  | [2024.02.01-19.38.26:994][  0]LogInit:  - bDontReuseConnections = false  - Libcurl will reuse connections
palworld-server  | [2024.02.01-19.38.26:994][  0]LogInit:  - MaxHostConnections = 16  - Libcurl will limit the number of connections to a host
palworld-server  | [2024.02.01-19.38.26:994][  0]LogInit:  - LocalHostAddr = Default
palworld-server  | [2024.02.01-19.38.26:994][  0]LogInit:  - BufferSize = 65536
palworld-server  | [2024.02.01-19.38.27:022][  0]CrashReportCoreLog: Sending HTTP request: https://o1291919.ingest.sentry.io/api/6513339/unreal/4a1a3921f51f4975b4cf8dd19022cb20/?AppID=CrashReporter&AppVersion=5.1.1-0%2B%2B%2BUE5%2BRelease-5.1&AppEnvironment=Release&UploadType=crashreports&UserID=87b36c89e5ce457292ef095eba013f36-000003e8%7C%7C87b36c89e5ce457292ef095eba013f36
palworld-server  | [2024.02.01-19.38.28:166][  0]CrashReportCoreLog: OnProcessRequestComplete(), State=SendingFiles bSucceeded=1
palworld-server  | [2024.02.01-19.38.28:166][  0]CrashReportCoreLog: State change from SendingFiles to SendingFiles
palworld-server  | [2024.02.01-19.38.28:166][  0]CrashReportCoreLog: All uploads done
palworld-server  | [2024.02.01-19.38.28:166][  0]CrashReportCoreLog: State change from SendingFiles to Finished
palworld-server  | [2024.02.01-19.38.28:800][  0]CrashReportCoreLog: Final state (Receiver) = Finished
palworld-server  | [2024.02.01-19.38.28:800][  0]CrashReportCoreLog: Final state (Receiver) = Unknown UploadState value
palworld-server  | [2024.02.01-19.38.28:803][  0]LogCore: Engine exit requested (reason: CrashReportClientApp RequestExit)
palworld-server  | [2024.02.01-19.38.28:803][  0]LogExit: Preparing to exit.
palworld-server  | [2024.02.01-19.38.28:844][  0]LogExit: Object subsystem successfully closed.
palworld-server  | [2024.02.01-19.38.28:901][  0]LogModuleManager: Shutting down and abandoning module HTTP (12)
palworld-server  | [2024.02.01-19.38.28:943][  0]LogModuleManager: Shutting down and abandoning module SSL (11)
palworld-server  | [2024.02.01-19.38.28:945][  0]LogModuleManager: Shutting down and abandoning module CrashDebugHelper (8)
palworld-server  | [2024.02.01-19.38.28:946][  0]LogModuleManager: Shutting down and abandoning module CoreUObject (6)
palworld-server  | [2024.02.01-19.38.28:946][  0]LogModuleManager: Shutting down and abandoning module PakFile (4)
palworld-server  | [2024.02.01-19.38.28:950][  0]LogModuleManager: Shutting down and abandoning module RSA (3)
palworld-server  | [2024.02.01-19.38.28:994][  0]LogExit: Exiting.
palworld-server  | dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
palworld-server  | Engine crash handling finished; re-raising signal 0 for the default handler. Good bye.

**Comment by jiannystein** [comment]
```
palworld-server | dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
palworld-server | Engine crash handling finished; re-raising signal 0 for the default handler. Good bye.
```
I encountered this error for the first time just a few minutes ago; the server has been running smoothly with daily reboots. This error has now occurred for the second time, and it happened within just a few minutes.

**Comment by thijsvanloef** [comment]
are the windows host and the linux host using the same hardware? 
The stacktrace you see in the logs is the same as https://github.com/thijsvanloef/palworld-server-docker/issues/252 which was introduced in 0.1.4.0 and not something i can fix sadly

**Comment by fadil05me** [comment]
hi man, idk if this will help but i was getting similar problem when i tried to move my server to linux server, before i move the saved data it runs fine. but then i tried to delete all the files in Saved folder and start the server again but it didn't make any new files at all. so i realize that i probably need to change permission for all files and folders in Saved folder to 777. it runs fine now

**Comment by YuZongYangHi** [comment]
@fadil05me Are there any other configurations? I don't think this is the reason
