### ISSUE TITLE
Engine.ini Settings update

### ISSUE THREAD

**Issue by samstiyer** [thijsvanloef/palworld-server-docker#257]
Hi I was curious if you would cover how to update the `Engine.ini`. Currently I see it gets overwritten on launch of the container, here is a reference to the settings I would like to update. I'm open to adding the altered file during the build if thats an option.

https://www.reddit.com/r/Palworld/comments/19f6i19/optimizing_palworld_dedicated_server_engineini/

**Comment by MSpreckels** [comment]
Hey there! We are currently planning and designing a way to easily set all the settings in #207. Setting settings in Engine.ini is still on the horizon but its planned
