### ISSUE TITLE
Anti cheating server, how to do it

### ISSUE THREAD

**Issue by pi135** [thijsvanloef/palworld-server-docker#268]
I once joined a Chinese server where the server could disable the transfer of hackers and item generation hackers, and there was a system that indicated that the person was a hacker. May I ask how it was done
![服务器1](https://github.com/thijsvanloef/palworld-server-docker/assets/106806368/2b25ffbe-47b6-4954-b2cb-fa9138035ad1)
![服务器2](https://github.com/thijsvanloef/palworld-server-docker/assets/106806368/d74ab784-c6c4-490e-8e70-646bdc357637)

**Comment by thijsvanloef** [comment]
@pi135 You are better off asking the owner of the server how they have done it. 
I am also not sure if they even run this docker container to host their server
