### ISSUE TITLE
Need debian 12 and inject PalWorld-Server-Unoffical-Api

### ISSUE THREAD

**Issue by liasica** [thijsvanloef/palworld-server-docker#269]
Hi, is it possible to upgrade the version to Debian12, because compiling [PalWorld-Server-Unoffical-Api](https://github.com/VeroFess/PalWorld-Server-Unoffical-Api) requires c++20.

**Comment by thijsvanloef** [comment]
Hi @liasica Since this image is build on `cm2network/steamcmd` which is Debian 11, this is not something that is planned, as upgrading to Debian 12 requires a different base image and possibly a refactor of the Dockerfile.

**Comment by liasica** [comment]
> Hi @liasica Since this image is build on `cm2network/steamcmd` which is Debian 11, this is not something that is planned, as upgrading to Debian 12 requires a different base image and possibly a refactor of the Dockerfile.

Okay, I understand. I can try to make my own mirror based on your mirror.
