### ISSUE TITLE
Crash Logs

### ISSUE THREAD

**Issue by Simpuhl** [thijsvanloef/palworld-server-docker#274]
Looks like crash logs are automatically uploaded, are you able to access them? Server has crashed multiple times for no apparent reason.

Then when I restart the server, my character is always stuck underground and I have to loose all my items to respawn. Also no bosses will spawn until I log off and back on sometimes. Even ones I have not killed in a few days (real life).

**Comment by thijsvanloef** [comment]
Hi @Simpuhl, crash logs are sent to the Palworld devs, I do not have access to them.
It seems like you are describing bugs within the server itself, this is not something I can fix sadly. Only the Palworld devs can.

**Comment by thijsvanloef** [comment]
@Simpuhl as for the being stuck underground bug, usually disconnecting and reconnecting again fixes this :)
