### ISSUE TITLE
Environmental Var for AdminPassword needs to be in ""

### ISSUE THREAD

**Issue by chaoscode** [thijsvanloef/palworld-server-docker#275]
## Describe the bug

I had the manually edit the ini file to put the "" around the password to get it to work.

**Comment by ThePrinoob** [comment]
Wanted to report that too. I had a & in my password and it always only wrote everything before. 
Using v0.21.0.

**Comment by win5923** [comment]
> Wanted to report that too. I had a & in my password and it always only wrote everything before. Using v0.21.0.

In Shell scripting, `&` is a special character used.
Not recommended to set a variable name as `&` because it may lead to confusion or unexpected behavior due to its special meaning in Shell syntax.

**Comment by win5923** [comment]
> had the manually edit the ini file to put the "" around the password to get it to work.

If you want to become an administrator, you must set the `AdminPassword`. If you simply don't want anyone to become an administrator, I can create a pull request (PR) to allow setting ADMIN_PASSWORD to an empty string.

**Comment by win5923** [comment]
> had the manually edit the ini file to put the "" around the password to get it to work.

If you want to become an administrator, you must set the `AdminPassword`. If you simply don't want anyone to become an administrator, I can create a PR to allow setting `AdminPassword` to an empty string through env `ADMIN_PASSWORD`

**Comment by thijsvanloef** [comment]
Sadly cannot get around the & at the moment, this is a limitation on using bash to set the settings. Hopefully https://github.com/thijsvanloef/palworld-server-docker/pull/207  is able to fix this later on

**Comment by MSpreckels** [comment]
Hey there does this issue persists after the latest update?

**Comment by chaoscode** [comment]
This is fixed. Thanks.
