### ISSUE TITLE
start.sh bug

### ISSUE THREAD

**Issue by AaronAgg** [thijsvanloef/palworld-server-docker#276]
## Describe the bug

Hello, I have found an issue with the .env variables and the start.sh "sed" filter in a variable.

The problem is that when you modify the variable "Death_Penalty" once you have started a docker, its getting wrong values because it is only filtering a-zA-Z values and adding it, so its ignoring the default "1" value and adding on top of it.

For example, I change this var to in my .env:

DEATH_PENALTY=Item

It does add in the generated .ini file "Item1".

The filter of the script must be changed to filter numerics also so it doesnt overlap

So in this scope in line 242 we need to change it:

if [ -n "${DEATH_PENALTY}" ]; then
    echo "DEATH_PENALTY=$DEATH_PENALTY"
    sed -E -i "s/DeathPenalty=**[a-zA-Z]***/DeathPenalty=$DEATH_PENALTY/" /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini
fi

I think it should work as **[a-zA-Z0-9]**

Thanks in advance!

**Comment by Dashboy1998** [comment]
> The problem is that when you modify the variable "Death_Penalty" once you have started a docker, its getting wrong values because it is only filtering a-zA-Z values and adding it, so its ignoring the default "1" value and adding on top of it.

I'm not sure why you have a default value of 1, it's default is All in the INI file.

**Comment by thijsvanloef** [comment]
@AaronAgg I do not have any number in my `DeathPenalty` setting, and that should not happen. This might still be a bug from the 0.18.0 version. 
Please make sure you are on the latest version (0.21.0): 

- docker compose down --rmi all
- docker compose up -d

If that does not work, please remove the PalWorldSettings.ini and restart the container.

Please reopen this issue if the issue persists
