### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by z499738316** [thijsvanloef/palworld-server-docker#28]
sh: 1: ./PalServer.sh: not found
*****STARTING SERVER*****Executing usermod...
usermod: no changes
/home/steam/steamcmd/steamcmd.sh: line 38: /home/steam/steamcmd/linux32/steamcmd: cannot execute binary file: Exec format error
*****STARTING INSTALL/UPDATE*****./PalServer.sh -port=8211 -players=16 -publicip=121.222.82.122 -publicport=8211 -servername=`REDACTED` -serverpassword=`REDACTED` -adminpassword=`REDACTED`
sh: 1: ./PalServer.sh: not found
*****STARTING SERVER*****Executing usermod...
usermod: no changes
/home/steam/steamcmd/steamcmd.sh: line 38: /home/steam/steamcmd/linux32/steamcmd: cannot execute binary file: Exec format error
*****STARTING INSTALL/UPDATE*****./PalServer.sh -port=8211 -players=16 -publicip=121.222.82.122 -publicport=8211 -servername=`REDACTED` -serverpassword=`REDACTED `-adminpassword=`REDACTED`
sh: 1: ./PalServer.sh: not found
*****STARTING SERVER*****Executing usermod...
usermod: no changes
/home/steam/steamcmd/steamcmd.sh: line 38: /home/steam/steamcmd/linux32/steamcmd: cannot execute binary file: Exec format error
*****STARTING INSTALL/UPDATE*****./PalServer.sh -port=8211 -players=16 -publicip=121.222.82.122 -publicport=8211 -servername=`REDACTED` -serverpassword=`REDACTED` -adminpassword=`REDACTED` 
sh: 1: ./PalServer.sh: not found
*****STARTING SERVER*********

**Comment by thijsvanloef** [comment]
On what device are you running this? Exec format error usually happens if you are running it on an ARM64 based server (Raspberry Pi/Oracle Ampere A1 etc.)

**Comment by z499738316** [comment]
Real x86_ 64 Runs this image

> 您在什么设备上运行它？如果您在基于 ARM64 的服务器（Raspberry Pi/Oracle Ampere A1 等）上运行它，通常会发生 Exec 格式错误

**Comment by z499738316** [comment]
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/37020005/daa669f1-41a3-4f65-aabb-0829b0947404)
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/37020005/14e7fba1-fb4d-484b-b9b9-9d3ff5fd3116)

**Comment by z499738316** [comment]
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/37020005/2a623f0e-4a5d-4a7a-81cb-d39d05100abf)

**Comment by z499738316** [comment]
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/37020005/4d789aff-d3c9-4fe4-8b2a-47809aa5b072)

**Comment by thijsvanloef** [comment]
You seem to be running IStoreOS, I'm not sure if my container is compatible with that OS.

**Comment by fynaltgn** [comment]
U know if is compatible with synology? I'm having trouble running it @thijsvanloef

**Comment by thijsvanloef** [comment]
@fynaltgn if you are having trouble with synology please open a new bug report so I can help you there: https://github.com/thijsvanloef/palworld-server-docker/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

**Comment by thadude3** [comment]
I saw this same issue on a freshly deployed image.
running on linux x86_64 Ubuntu 20.04.6 LTS

**Comment by z499738316** [comment]
It may be because the steamcmd program is 32-bit, causing it to fail to run

**Comment by thadude3** [comment]
> I saw this same issue on a freshly deployed image. running on linux x86_64 Ubuntu 20.04.6 LTS

in my case it was user error. steamcmd was failing because I didn't have enough diskspace.
"Error! App '2394010' state is 0x202 after update job."

**Comment by JakeCooper** [comment]
Running into this with the latest image attempting to deploy on Railway

**Comment by hengwuming** [comment]
I have the same problem. Have you solved it?

**Comment by thijsvanloef** [comment]
@z499738316 For now I can only recommend you try to setup a server without docker to see if this issue persists. If it does not persist it is an issue with my container. If you get the same error, it is an issue for the Palworld devs. Please reopen this issue if you need further assistance.
