### ISSUE TITLE
When i use other Supervisor which use rcon to brodcast restart service,rcon connection refused 

### ISSUE THREAD

**Issue by AprDeci** [thijsvanloef/palworld-server-docker#282]
maybe you set it just can use in cil itself or my wrong setting,can you tell me what can i do

**Comment by thijsvanloef** [comment]
Please share your config. The problem probably lies with the fact that the container does not open port 25575 to the outside by default and you need to open it:
```yaml
ports:
  - 8211:8211/udp
  - 27015:27015/udp
  - 25575:25575/tcp
```

**Comment by AprDeci** [comment]
😵my bad,i set udp port，i will try it again tomorrow,then i will reply u,thanks
