### ISSUE TITLE
Server version downgrade

### ISSUE THREAD

**Issue by slhx99** [thijsvanloef/palworld-server-docker#285]
Hey all, I accidentally updated my server from v0.1.3.0 to v0.1.4.0, I was trying to figure out how I can downgrade the server back to v0.1.3.0 so that I can play with my friends as v0.1.4.0 is very unstable for my friends and I

I've tried following [this guide](https://steamcommunity.com/sharedfiles/filedetails/?id=1086279994), used steamcmd to download the v0.1.3.0 server using this command `download_depot 2394010 2394012 4190579964382773830`, and moved the files to the /palworld/ folder to replace the v0.1.4.0 files.

I've restarted the docker afterwards and entered the server in-game. I realised that the game was still showing v0.1.4.0, supported by the docker rcon-cli `info` command which showed it being a v.0.1.4.0 server.

Am I missing anything? Or is there a simpler way to downgrade the server? Where should I replace the v0.1.3.0 files to? Are there additional steps that I've missed?

**Comment by zapoqx** [comment]
I'm pretty sure by the design of this docker that its supposed to check for updates and download the latest version before it activates the server program.  You're basically asking to have a version option that needs to be read for the steamcmd to just match.

**Comment by slhx99** [comment]
Update: I just realised that the manifest ID that I used is the v0.1.4.0 one, and I've found the v0.1.3.0 one.
I've used the command `download_depot 2394010 2394012 1354752814336157338` and replaced the /palworld/ folder with the actual v0.1.3.0 files and set `UPDATE_ON_BOOT` to `false` and it works now!

**Comment by tam11a** [comment]
@slhx99 The game is now in v0.1.4.1 and I want to downgrade it to v0.1.4.0. can you help me with it? my discord handle is "tam.11a". please knock if you can.

**Comment by slhx99** [comment]
I've sent a friend request (slhx) over in discord!

**Comment by tam11a** [comment]
> @tam11a I've sent a friend request (slhx) over in discord!

Found it.

**Comment by slhx99** [comment]
@Sitouxz @tam11a 
Before I started the downgrade:

1. I made sure that I have `AUTO_UPDATE_ENABLED=false` in my environment variable.
If you have yet to do so, do have this environment variable added and update your container prior to starting this.
3. I made sure that nobody was on during the server downgrade process.

Here are the list of executes that I've made to downgrade my server:
1. ssh into your palworld-server container with the user steam
Replace `<palworld-server>` with your  palworld-server container name
```shell
sudo docker exec -it -u steam <palworld-server> sh
```
2. save your server progress.
I used rcon-cli to save the server's progress:
```shell
~/server/rcon-cli
```
```shell
save
```
to exit rcon-cli, use this command:
```shell
:q
```
4. To perform the server downgrade, I made this following command to install my desired server version:
Do replace `<ManifestID>` (in line 2 as shown below) with the server version that you desire.
The ManifestIDs of palworld-server can be found [here](https://steamdb.info/depot/2394012/manifests/) where the dates corresponds closely to the server versions.
Below are some of the example ManifestIDs:
> [4190579964382773830](https://steamdb.info/depot/2394012/history/?changeid=M:4190579964382773830) for 0.1.4.0
> [1354752814336157338](https://steamdb.info/depot/2394012/history/?changeid=M:1354752814336157338) for 0.1.3.0
```shell
~/steamcmd/steamcmd.sh +@sSteamCmdForcePlatformType linux +@sSteamCmdForcePlatformBitness 64 +login anonymous \
+download_depot 2394010 2394012 <ManifestID> &&
cp -rf ~/steamcmd/linux32/steamapps/content/app_2394010/depot_2394012/* /palworld/ &&
rm -rf ~/steamcmd/linux32/steamapps/content/app_2394010/depot_2394012/*
```
4. I then shut the server down to finish the server downgrade.
via rcon-cli:
```shell
~/server/rcon-cli
```
```shell
shutdown 1
```
```shell
:q
```
or use the auto-reboot function:
```shell
~/server/auto-reboot.sh
``` 
5. your server should restart and reflect the downgrade if your restart policy is set to `always` or `unless-stopped`.
you can check the palworld-server version via rcon-cli if you ssh into your palworld-server after the restart:
```shell
~/server/rcon-cli
```
```shell
info
```

**Comment by Jihed2004** [comment]
@slhx99  The game is now in v0.1.4.1 and I want to downgrade the server  to v0.1.4.0 what should i do ?

**Comment by slhx99** [comment]
> @slhx99 The game is now in v0.1.5.1 and I want to downgrade the server to v0.1.4.0 what should i do ?

I'm pretty sure that the dev has incorporate this feature into the latest docker build. so you'll just have to find the Manifest ID of v0.1.4.0 (which is [4190579964382773830](https://steamdb.info/depot/2394012/history/?changeid=M:4190579964382773830)) and add it to your `TARGET_MANIFEST_ID` environment variable.

**Comment by Jihed2004** [comment]
> > @slhx99 The game is now in v0.1.5.1 and I want to downgrade the server to v0.1.4.0 what should i do ?
> 
> I'm pretty sure that the dev has incorporated this feature into the latest docker build. so you'll just have to find the Manifest ID of v0.1.4.0 (which is [4190579964382773830](https://steamdb.info/depot/2394012/history/?changeid=M:4190579964382773830)) and add it to your `TARGET_MANIFEST_ID` environment variable.

can i contact u via discord 
this is mine :estakooza

**Comment by thijsvanloef** [comment]
@Jihed2004 https://palworld-server-docker.loef.dev/guides/pinning-game-version :)

**Comment by thijsvanloef** [comment]
@Jihed2004 If you need assistance you can also join this projects discord https://discord.com/invite/UxBxStPAAE
