### ISSUE TITLE
Unable to Locate Game Files

### ISSUE THREAD

**Issue by rzajeski** [thijsvanloef/palworld-server-docker#286]
## Describe the bug

I have had a server running for the past 2 days, but there are no game/save/player files anywhere on my NAS.  

## To Reproduce

![image](https://github.com/thijsvanloef/palworld-server-docker/assets/78763261/11db1653-55a5-4210-852e-3049d24b5828)

Volume is set to /docker/Configs/Palworld, but no game files exist in this directory location.

## Actual behavior

![image](https://github.com/thijsvanloef/palworld-server-docker/assets/78763261/ddadac93-0da5-4d51-a240-d39440a54df5)

## OS information

- OS:  DSM 7.2
- Palworld Version:  0.1.4.0
- Docker Image Version:  0.21.0

## Hardware information

Synology DS224+

## docker-compose.yml contents
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      stop_grace_period: 30s # Set to however long you are willing to wait for the container to gracefully stop
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      env_file:
         -  env.env
      volumes:
         - /docker/Configs/Palworld

**Comment by MSpreckels** [comment]
Hey, 
You did not map a folder to your volumes, you need to specify a local path and a path in the docker container like


```
      volumes:
         - <local-path>:/palworld/
```

So something like

```
      volumes:
         - /docker/Configs/Palworld:/palworld/
```

CAREFUL: If you shutdown your server all your data will be lost. I suggest to copy the palworld folder to your local machine and then fix the compose

```
docker cp palworld:/palworld/ /docker/Configs/Palworld
```

**Comment by rzajeski** [comment]
> Hey, You did not map a folder to your volumes, you need to specify a local path and a path in the docker container like
> 
> ```
>       volumes:
>          - <local-path>:/palworld/
> ```
> 
> So something like
> 
> ```
>       volumes:
>          - /docker/Configs/Palworld:/palworld/
> ```
> 
> CAREFUL: If you shutdown your server all your data will be lost. I suggest to copy the palworld folder to your local machine and then fix the compose
> 
> ```
> docker cp palworld:/palworld/ /docker/Configs/Palworld
> ```

Thanks! I was worried that something like this was the case.
When I ssh into my account and paste that line to copy files, it gives me this error:
`invalid output path: directory "/docker/Configs" does not exist`

**Comment by MSpreckels** [comment]
You ran the docker command at the same place where you ran the docker-compose command? Im not too familiar with running docker on Synology.

You could always use another folder to save your data and move it later

**Comment by rzajeski** [comment]
> You ran the docker command at the same place where you ran the docker-compose command? Im not too familiar with running docker on Synology.
> 
> You could always use another folder to save your data and move it later

I just started with the synology a couple of weeks ago, it's a bit foreign to me.  I created a project called palworld-server with the docker-compose.yml pasted above and used a file called env.env to pull all of my desired environment variables.

For the docker cp line I went into the terminal on my PC, ssh into my account, and then pasted it.  Not sure if there's a place that can be pasted within Container Manager instead?

**Comment by MSpreckels** [comment]
Quick google says there isn't. 

you could also just copy it first and move later:

```
mkdir Palworld
docker cp palworld:/palworld/ ./Palworld
```

What does `ls /docker` show ?

**Comment by rzajeski** [comment]
> Quick google says there isn't.
> 
> you could also just copy it first and move later:
> 
> ```
> mkdir Palworld
> docker cp palworld:/palworld/ ./Palworld
> ```
> 
> What does `ls /docker` show ?

![image](https://github.com/thijsvanloef/palworld-server-docker/assets/78763261/f2b0c5b9-4756-4638-b5b1-9c78fc5aacef)

Here's what I get.  Mkdir worked and I now see the Palworld folder under my home directory, but the second line will not execute

**Comment by MSpreckels** [comment]
Oh try 

`sudo`

`sudo docker cp palworld:/palworld/ ./Palworld` and `sudo ls /docker`

**Comment by rzajeski** [comment]
> Oh, try `sudo`
> 
> `sudo docker cp palworld:/palworld/ ./Palworld` and `sudo ls /docker`

![image](https://github.com/thijsvanloef/palworld-server-docker/assets/78763261/4266121f-b650-41b4-93c8-11ba1e25c179)

Not sure if this helps, but in my palworld-server container it shows the following directory:
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/78763261/55f56c13-974c-472b-b1fe-e9f9cbdd7699)

Thanks for helping out by the way! This is very foreign to me

**Comment by MSpreckels** [comment]
your container might now be named palworld. Can you check with docker container ls?

**Comment by rzajeski** [comment]
Update: Got it to work with the following modification:

`sudo docker cp palworld-server:/palworld/ ./Palworld`

My container was named palworld-server, that was my issue! Next time I am following the guides exactly as described lol, I tried to keep naming consistent with the other projects I have.

Thanks so much for the help! My friends and I appreciate that we won't have to start over
