### ISSUE TITLE
Running in Kubernetes Connecting Through DNS, Can't Reconnect via Recent Servers

### ISSUE THREAD

**Issue by gzukel** [thijsvanloef/palworld-server-docker#294]
## Describe the bug

We have two servers running.
One on a physical machine, the other running in Kubernetes through a network load balancer in AWS.

I can connect to my node world.palworld-servers.io but I can't re-connect through recent servers just gives me connection error. However if I put the dns again in direct connect it will connect right away.

For the one running on a physical machine with dedicated IP it re-connects just fine. 

I wonder if its related to the traffic going through the load balancer in K8S because its a DNS and not IP and through AWS non dedicated IP's. The Load Balancer IP hasn't changed but I wonder if its porking it. Not sure any help here would be helpful.

**Comment by thijsvanloef** [comment]
@gzukel don't worry about the labels! @Filipe-Souza If you have the time, could you shed some light on the issue?

**Comment by Filipe-Souza** [comment]
I had this error too on some game clients, ended up guiding the users to just reconnect with the same data. I tought that was a game client issue only (happens when you using only IPv4 too, not only hostnames).
