### ISSUE TITLE
Migrating server from one platform to another (MacOS to Linux)

### ISSUE THREAD

**Issue by WisdomSky** [thijsvanloef/palworld-server-docker#298]
Not really an issue but I just want to ask how can we migrate the data (the volume containing the data in the container's `/palworld` directory) from (let's say) MacOS into Linux?

Which things do I need to only copy? or is it fine to just copy everything and then boot it up in the new platform and the image will be able to handle it automatically?

I'm currently running a Palworld server on a MacOS and now wants to migrate it to my Linux machine without losing any data.

Also, thank you for everyone who's involved in this project, it runs really well and had zero problems with it since I've started running my 3 dedicated servers with this. 🙏

Thanks,

**Comment by win5923** [comment]
check the following link：


https://www.reddit.com/r/Palworld/comments/19cn44w/guide_how_to_correctly_transfer_saved_data_across/?utm_source=share&utm_medium=ios_app

**Comment by WisdomSky** [comment]
> check the following link：
> 
> https://www.reddit.com/r/Palworld/comments/19cn44w/guide_how_to_correctly_transfer_saved_data_across/?utm_source=share&utm_medium=ios_app

Has this "hacky" approach been confirmed working? 
This also means that I have to let the container initialize prior to overwriting the new data with my saved/old data.

There are also some people in the comments complaining that it does not 100% fully work and loses some data like each player's waypoints.

**Comment by win5923** [comment]
I've tested transitioning from Windows to Linux and is feasible, but I'm unsure about macOS.

**Comment by WisdomSky** [comment]
> I've tested migrating from Windows to Linux and is feasible, but I'm unsure about macOS.

Ohhh. I guess I'll have to try it first.
