### ISSUE TITLE
Discord Webhook: add support for mentions

### ISSUE THREAD

**Issue by ThePrinoob** [thijsvanloef/palworld-server-docker#300]
**Is your feature request related to a problem? Please describe.**
I wanted to mention a certain role on my discord server so not everyone gets the notifications who has access. I found out that you can mention roles by adding this to the message:
`<@&XXXXXXXXXXXXXX>`

But this is not working because the message is sent in the title of the embed.

**Describe the solution you'd like**
I want that you can define a ENV variable where you can define mentions which are then sent in the description of the message.

**Describe alternatives you've considered**
Alternatively the message could also be sent in the description and the mention would be in the message too. The title would be something like "Palworld Server" or whatever :)

**Additional context**
How to mention a role: [here](https://stackoverflow.com/questions/58749366/how-do-i-mention-a-role-with-discord-js)
Discord Webhook live parser: [here](https://discohook.org/)

**Comment by v4de** [comment]
This is a very cool idea, right now the json I am building is pretty simple.

```sh
JSON=$(jo embeds[]="$(jo title="$MESSAGE" color=$COLOR)")
```

We can modify it to:

```sh
JSON=$(jo embeds[]="$(jo title="$TITLE" description="$MESSAGE" color=$COLOR)")
```

Can create a new title for each one instead, or completely scrap the title? What do you think?

**Comment by Luatan** [comment]
> This is a very cool idea, right now the json I am building is pretty simple.
> 
> ```shell
> JSON=$(jo embeds[]="$(jo title="$MESSAGE" color=$COLOR)")
> ```
> 
> We can modify it to:
> 
> ```shell
> JSON=$(jo embeds[]="$(jo title="$TITLE" description="$MESSAGE" color=$COLOR)")
> ```
> 
> Can create a new title for each one instead, or completely scrap the title? What do you think?

How about if the title would be the script or function for example: Backup, Update and so on. Then the description can be what the script is doing.
