### ISSUE TITLE
Spelling in .env.example

### ISSUE THREAD

**Issue by eth0h4ckr** [thijsvanloef/palworld-server-docker#317]
Sorry this is gonna be short but i noticed the following does not get applied to Palworldsettings due to spelling (DECREASE vs DECREACE). Updating to DECREACE for the following VARS fixes the issue. There are prob more spelling mistakes but these are what I wanted to fix.

#Current
- PAL_STAMINA_DECREASE_RATE=0.4
- PLAYER_STAMINA_DECREASE_RATE=0.4

#Needs to be
- PAL_STAMINA_DECREACE_RATE=0.4
- PLAYER_STAMINA_DECREACE_RATE=0.4

**Comment by thijsvanloef** [comment]
Yup, you're right, working on it now

**Comment by thijsvanloef** [comment]
Fixed in 0.24.2

**Comment by eth0h4ckr** [comment]
Thank you!
