### ISSUE TITLE
Documentation for configuring arbitrary PalWorldSettings.ini settings as Environment Variables

### ISSUE THREAD

**Issue by ax-vasquez** [thijsvanloef/palworld-server-docker#323]
**Is your feature request related to a problem? Please describe.**
It wasn't clear to me what the proper way to customize the `PalWorldSettings.ini` file. Initially, I was simply modifying the contents of the file in `Pal/Saved/Config/LinuxServer/PalWorldSettings.ini`, which had worked until the latest update.

I poked around for a while and finally realized that these settings can be set as environment variables. For example, to set `PalEggDefaultHatchingTime`, you would add `PAL_EGG_DEFAULT_HATCHING_TIME` as an environment variable for the container running the image and just configure it there.

**Describe the solution you'd like**
Just a small note in the Environment Variables section of the documentation discussing how to pass variables for settings outlined here:
* https://palworld.wiki.gg/wiki/PalWorldSettings.ini

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MSpreckels** [comment]
Hi there,
there already is a list of possible env vars [here](https://github.com/thijsvanloef/palworld-server-docker?tab=readme-ov-file#environment-variables) and [here](https://github.com/thijsvanloef/palworld-server-docker?tab=readme-ov-file#with-environment-variables). 

Issue #326 allows to disable the automatic settings creation.

Is there something missing?

**Comment by MSpreckels** [comment]
I've opened #328 to add more explanations. Is that ok?

**Comment by ax-vasquez** [comment]
> I've opened #328 to add more explanations. Is that ok?

Oh I hadn't seen this! Perfect 👍
