### ISSUE TITLE
Flexible discord notification

### ISSUE THREAD

**Issue by Torotin** [thijsvanloef/palworld-server-docker#324]
Greetings.
I suggest introducing separate variables for Discord messages about working with backups.

DISCORD_BACKUP={true|false}
DISCORD_BACKUP_WEBHOOK_URL="{STRING}"
DISCORD_PRE_BACKUP_MSG="{STRING}"
DISCORD_BACKUP_OK_MSG="{STRING}"
DISCORD_BACKUP_ERROR_MSG="{STRING}"
DISCORD_PRE_BACKUP_DELETE_MSG="{STRING}"
DISCORD_BACKUP_OK_DELETE_MSG="{STRING}"
DISCORD_BACKUP_BACKUP_ERROR_DELETE_MSG="{STRING}"

This change will allow for more flexible notification flows: for users (players) - only server status, and for admins - variable enabling/disabling of notifications with the possibility of directing them to a separate admin channel.

**Comment by jiannystein** [comment]
Just to share and gather any additional insights on how others are doing their things on this topic

My Docker webhook is configured to notify the admin's channel. Here's what it looks like at the moment for backup:
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/41028418/b4bc6ab8-fa95-4ff3-8f2d-09d785832b71)

Script for notifying the public channel and broadcasting via RCON, as well as restarting the server when memory usage exceeds 90%, to prevent unexpected interruptions:
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/41028418/9dae2415-19f8-4b65-9550-3a445a11739d)

Script for notifying the public join/leave channel and broadcasting via RCON when a player joins or leaves:
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/41028418/b1ace498-bd68-4e95-8c66-4273597bed9f)

**Comment by thijsvanloef** [comment]
@Torotin @jiannystein I'm currently working on this enhancement, if you could, could you test this image? `thijsvanloef/palworld-server-docker:pr-490`
| Variable                                   | Info                                                                                                                                                                                                | Default Values                                                                                         | Allowed Values                                                                                                    |
|--------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------|
| DISCORD_PRE_UPDATE_BOOT_MESSAGE            | Discord message sent when server begins updating                                                                                                                                                    | Server is updating...                                                                                  | "string"                                                                                                          |
| DISCORD_PRE_UPDATE_BOOT_MESSAGE_ENABLED    | If the Discord message is enabled for this message                                                                                                                                                  | true                                                                                                   | boolean                                                                                                           |
| DISCORD_PRE_UPDATE_BOOT_MESSAGE_URL        | Discord Webhook URL for this message (if left empty will use DISCORD_WEBHOOK_URL)                                                                                                                   |                                                                                                        | "string"                                                                                                          |
| DISCORD_POST_UPDATE_BOOT_MESSAGE           | Discord message sent when server completes updating                                                                                                                                                 | Server update complete!                                                                                | "string"                                                                                                          |
| DISCORD_POST_UPDATE_BOOT_MESSAGE_ENABLED   | If the Discord message is enabled for this message                                                                                                                                                  | true                                                                                                   | boolean                                                                                                           |
| DISCORD_POST_UPDATE_BOOT_MESSAGE_URL       | Discord Webhook URL for this message (if left empty will use DISCORD_WEBHOOK_URL)                                                                                                                   |                                                                                                        | "string"                                                                                                          |
| DISCORD_PRE_START_MESSAGE                  | Discord message sent when server begins to start                                                                                                                                                    | Server has been started!                                                                               | "string"                                                                                                          |
| DISCORD_PRE_START_MESSAGE_ENABLED          | If the Discord message is enabled for this message                                                                                                                                                  | true                                                                                                   | boolean                                                                                                           |
| DISCORD_PRE_START_MESSAGE_URL              | Discord Webhook URL for this message (if left empty will use DISCORD_WEBHOOK_URL)                                                                                                                   |                                                                                                        | "string"                                                                                                          |
| DISCORD_PRE_SHUTDOWN_MESSAGE               | Discord message sent when server begins to shutdown                                                                                                                                                 | Server is shutting down...                                                                             | "string"                                                                                                          |
| DISCORD_PRE_SHUTDOWN_MESSAGE_ENABLED       | If the Discord message is enabled for this message                                                                                                                                                  | true                                                                                                   | boolean                                                                                                           |
| DISCORD_PRE_SHUTDOWN_MESSAGE_URL           | Discord Webhook URL for this message (if left empty will use DISCORD_WEBHOOK_URL)                                                                                                                   |                                                                                                        | "string"                                                                                                          |
| DISCORD_POST_SHUTDOWN_MESSAGE              | Discord message sent when server has stopped                                                                                                                                                        | Server is stopped!                                                                                     | "string"                                                                                                          |
| DISCORD_POST_SHUTDOWN_MESSAGE_ENABLED      | If the Discord message is enabled for this message                                                                                                                                                  | true                                                                                                   | boolean                                                                                                           |
| DISCORD_POST_SHUTDOWN_MESSAGE_URL          | Discord Webhook URL for this message (if left empty will use DISCORD_WEBHOOK_URL)                                                                                                                   |                                                                                                        | "string"                                                                                                          |
| DISCORD_PLAYER_JOIN_MESSAGE                | Discord message sent when player joins the server                                                                                                                                                   | \${player_name} has joined Palworld!                                                                   | "string"                                                                                                          |
| DISCORD_PLAYER_JOIN_MESSAGE_ENABLED        | If the Discord message is enabled for this message                                                                                                                                                  | true                                                                                                   | boolean                                                                                                           |
| DISCORD_PLAYER_JOIN_MESSAGE_URL            | Discord Webhook URL for this message (if left empty will use DISCORD_WEBHOOK_URL)                                                                                                                   |                                                                                                        | "string"                                                                                                          |
| DISCORD_PLAYER_LEAVE_MESSAGE               | Discord message sent when player leaves the server                                                                                                                                                  | \${player_name} has left Palworld.                                                                     | "string"                                                                                                          |
| DISCORD_PLAYER_LEAVE_MESSAGE_ENABLED       | If the Discord message is enabled for this message                                                                                                                                                  | true                                                                                                   | boolean                                                                                                           |
| DISCORD_PLAYER_LEAVE_MESSAGE_URL           | Discord Webhook URL for this message (if left empty will use DISCORD_WEBHOOK_URL)                                                                                                                   |                                                                                                        | "string"                                                                                                          |
| DISCORD_PRE_BACKUP_MESSAGE                 | Discord message when starting to create a backup                                                                                                                                                    | Creating backup...                                                                                     | "string"                                                                                                          |
| DISCORD_PRE_BACKUP_MESSAGE_ENABLED         | If the Discord message is enabled for this message                                                                                                                                                  | true                                                                                                   | boolean                                                                                                           |
| DISCORD_PRE_BACKUP_MESSAGE_URL             | Discord Webhook URL for this message (if left empty will use DISCORD_WEBHOOK_URL)                                                                                                                   |                                                                                                        | "string"                                                                                                          |
| DISCORD_POST_BACKUP_MESSAGE                | Discord message when a backup has been made                                                                                                                                                         | Backup created at \${FILE_PATH}                                                                        | "string"                                                                                                          |
| DISCORD_POST_BACKUP_MESSAGE_ENABLED        | If the Discord message is enabled for this message                                                                                                                                                  | true                                                                                                   | boolean                                                                                                           |
| DISCORD_POST_BACKUP_MESSAGE_URL            | Discord Webhook URL for this message (if left empty will use DISCORD_WEBHOOK_URL)                                                                                                                   |                                                                                                        | "string"                                                                                                          |
| DISCORD_PRE_BACKUP_DELETE_MESSAGE          | Discord message when starting to remove older backups                                                                                                                                               | Removing backups older than \${OLD_BACKUP_DAYS} days                                                   | "string"                                                                                                          |
| DISCORD_PRE_BACKUP_DELETE_ENABLED          | If the Discord message is enabled for this message                                                                                                                                                  | true                                                                                                   | boolean                                                                                                           |
| DISCORD_PRE_BACKUP_DELETE_URL              | Discord Webhook URL for this message (if left empty will use DISCORD_WEBHOOK_URL)                                                                                                                   |                                                                                                        | "string"                                                                                                          |
| DISCORD_POST_BACKUP_DELETE_MESSAGE         | Discord message when successfully removed older backups                                                                                                                                             | Removed backups older than \${OLD_BACKUP_DAYS} days                                                    | "string"                                                                                                          |
| DISCORD_POST_BACKUP_DELETE_ENABLED         | If the Discord message is enabled for this message                                                                                                                                                  | true                                                                                                   | boolean                                                                                                           |
| DISCORD_POST_BACKUP_DELETE_URL             | Discord Webhook URL for this message (if left empty will use DISCORD_WEBHOOK_URL)                                                                                                                   |                                                                                                        | "string"                                                                                                          |
| DISCORD_ERR_BACKUP_DELETE_MESSAGE          | Discord message when there has been an error removing older backups                                                                                                                                 | Unable to delete old backups, OLD_BACKUP_DAYS is not an integer. OLD_BACKUP_DAYS=\${OLD_BACKUP_DAYS}   | "string"                                                                                                          |
| DISCORD_ERR_BACKUP_DELETE_ENABLED          | If the Discord message is enabled for this message                                                                                                                                                  | true                                                                                                   | boolean                                                                                                           |
| DISCORD_ERR_BACKUP_DELETE_URL              | Discord Webhook URL for this message (if left empty will use DISCORD_WEBHOOK_URL)                                                                                                                   |                                                                                                        |
