### ISSUE TITLE
Create switch to allow manual configuration of .ini files

### ISSUE THREAD

**Issue by thijsvanloef** [thijsvanloef/palworld-server-docker#326]
**Is your feature request related to a problem? Please describe.**
The last update forced everyone to use environment files. I would like to see an option that allows users to turn automatic setting generation off if they would like.

**Describe the solution you'd like**
Setting an env var like MANUAL_SETTING_CONFIG=true to prevent the compile-setting.sh script from running

**Describe alternatives you've considered**
None

**Comment by MSpreckels** [comment]
What default behaviour would you like to see? Create settings automatically by default?

**Comment by thijsvanloef** [comment]
Most people would not like to mess around with .ini files, so in my opinion by default it should be generated automatically
