### ISSUE TITLE
"After updating the container and the server, a bug appeared."

### ISSUE THREAD

**Issue by PQ0000** [thijsvanloef/palworld-server-docker#338]
"When I use the rcon-cli command, the following message is displayed."

docker exec -it palworld-server rcon-cli ShowPlayers
cli: config: parse file: yaml: line 1: did not find expected key

docker logs -f palworld-server
*****EXECUTING USERMOD*****
usermod: no changes
*****GENERATING CONFIGS*****
Compiling PalWorldSettings.ini...
Compiling PalWorldSettings.ini done!
*****STARTING INSTALL/UPDATE*****
tid(29) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
[----] Download complete.
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
tid(41) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...OK
"@sSteamCmdForcePlatformType" = "linux"
"@sSteamCmdForcePlatformBitness" = "64"

Connecting anonymously to Steam Public...Retrying. . .
Retrying. . .
Retrying. . .
Retrying. . .
FAILED (No Connection)
BACKUP_ENABLED=true
AUTO_UPDATE_ENABLED=true
*****STARTING SERVER*****
./PalServer.sh -port=8211 -queryport=27015 EpicApp=PalServer -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
time="2024-02-09T04:03:35+08:00" level=info msg="read crontab: /home/steam/server/crontab"
Shutdown handler: initalize.
Increasing per-process limit of core file size to infinity.
- Existing per-process limit (soft=18446744073709551615, hard=18446744073709551615) is enough for us (need only 18446744073709551615)
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
Setting breakpad minidump AppID = 2394010
[S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
cli: config: parse file: yaml: line 1: did not find expected key
cli: config: parse file: yaml: line 1: did not find expected key
*****EXECUTING USERMOD*****
usermod: no changes
*****GENERATING CONFIGS*****
Compiling PalWorldSettings.ini...
Compiling PalWorldSettings.ini done!
*****STARTING INSTALL/UPDATE*****
tid(29) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...OK
"@sSteamCmdForcePlatformType" = "linux"
"@sSteamCmdForcePlatformBitness" = "64"

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) verifying install, progress: 36.39 (822612504 / 2260368082)
 Update state (0x5) verifying install, progress: 76.78 (1735514843 / 2260368082)
Success! App '2394010' fully installed.
BACKUP_ENABLED=true
AUTO_UPDATE_ENABLED=true
*****STARTING SERVER*****
./PalServer.sh -port=8211 -queryport=27015 EpicApp=PalServer -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
time="2024-02-09T08:58:19+08:00" level=info msg="read crontab: /home/steam/server/crontab"
Shutdown handler: initalize.
Increasing per-process limit of core file size to infinity.
- Existing per-process limit (soft=18446744073709551615, hard=18446744073709551615) is enough for us (need only 18446744073709551615)
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
CAppInfoCacheReadFromDiskThread took 1 milliseconds to initialize
Setting breakpad minidump AppID = 2394010
[S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.

**Comment by PQ0000** [comment]
/home/steam/server# nano rcon.yaml


default:
  address: "127.0.0.1:25575"
  password: ""xxxxxx""

**Comment by PQ0000** [comment]
i think find ti   哈哈

**Comment by thijsvanloef** [comment]
@PQ0000 Could you share your solution?

**Comment by Luatan** [comment]
I noticed, that if you use `- ADMIN_PASSWORD="yourpassword"` In the docker compose since the version v0.24.1 This error happens, because it uses the double quotes twice in the rcon config. 

This is also the case in all other strings, like discord hook and so on. Before this version there were quotes in the docker compose example, which would lead to this problem if you update your container.

**Comment by pmunozroa** [comment]
Hello, I was checking reddit I found something useful, setting config PalWorldSettings.ini to readonly will help, it kept everything after restart and rcon back to work
