### ISSUE TITLE
PalWorldSettings.ini changed on startup

### ISSUE THREAD

**Issue by chaoscode** [thijsvanloef/palworld-server-docker#340]
## Describe the bug

Modifying the settings in the ini, specifically PalEggDefaultHatchingTime, get reset on startup of the server to 72.0 from 1.0
When the server is stopped, its changed back to 1.0

## To Reproduce

1: Stop server
2: Modify \palworld\Pal\Saved\Config\LinuxServer\PalWorldSettings.ini
3: Start server
4: Obverse the ini change.
5: Stop server
6: Obverse the ini change.

## Expected behavior
For the ini to not change and start the way its set.

## Actual behavior
ini is changed on startup

## OS information

- OS:  TrueNAS Scale Docker 
- Palworld Version:  1.4.1
- Docker Image Version:  latest

## Hardware information

- CPU: Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz
- Memory:  128g

**Comment by thijsvanloef** [comment]
This behavior is expected since update 0.24.0, all the config changes should be done by env vars:
https://github.com/thijsvanloef/palworld-server-docker/releases/tag/0.24.0

**Comment by thijsvanloef** [comment]
@chaoscode no worries
