### ISSUE TITLE
Automated Docker Container Tests

### ISSUE THREAD

**Issue by thijsvanloef** [thijsvanloef/palworld-server-docker#343]
This serves as a thread to think about how to implement automated testing for the palworld-server-docker container to catch errors early and prevent the need for hotfixes.

## What to test:
- If the container builds successfully
- If the container runs successfully
- If port 8211, 27015 and 25575 are listening
- Backup command functions and creates a backup file
- PalWorldSettings.ini is valid

## How to test?
???

If you have any more ideas, please feel free to add :)

**Comment by Luatan** [comment]
I think what you also could test for, is if Rcon works and if the rcon-cli config file is valid.

**Comment by Phelms215** [comment]
Docker Hub's automated testing seems like the easiest way to implement testing. 
https://docs.docker.com/docker-hub/builds/automated-testing/
