### ISSUE TITLE
When restoring backup removing server password doesn't work.

### ISSUE THREAD

**Issue by gzukel** [thijsvanloef/palworld-server-docker#348]
## Describe the bug

I restored the data from one server to another the issue is the server I restored had a password. I checked the configuration file of the server I restored data too and useAuth is false and the server password is not set. However, when I try to join the server I restored to I have to use the password from the server I restored from even though its not set in the ini file. 

## To Reproduce

1. start a server with passwrod, take a tar of the palworld directory
2. start a new server without a password, restore the tar file 
3. you will then only be able to login with the password from first server even if the ini file is set to not use auth and no password is set.

**Comment by win5923** [comment]
Do you have WorldOption.sav in `palworld/Pal/Saved/SaveGames` path?
The file will ignore the `PalWorldSettings.ini` file generated from those env vars.
