### ISSUE TITLE
cant use old saved data

### ISSUE THREAD

**Issue by larrydemons** [thijsvanloef/palworld-server-docker#36]
root@VM-0-16-ubuntu:/home/ubuntu/palworld-server-docker/palworld/Pal/Saved/SaveGames/0# pwd
/home/ubuntu/palworld-server-docker/palworld/Pal/Saved/SaveGames/0
root@VM-0-16-ubuntu:/home/ubuntu/palworld-server-docker/palworld/Pal/Saved/SaveGames/0# ls
6A5B1DE2340E4AE889CEDF02AB841D4B  BF04C2E8C73A43B2AE22E3E52875BB9B

here i got two saved files 6A5B1DE2340E4AE889CEDF02AB841D4B is new,BF04C2E8C73A43B2AE22E3E52875BB9B is older one

i ran docker-compose up -d with palworld exist and only BF04C2E8C73A43B2AE22E3E52875BB9B in SaveGames

after container running ,it created new dir 6A5B1DE2340E4AE889CEDF02AB841D4B, whatever i delete this and restart the container this dir  6A5B1DE2340E4AE889CEDF02AB841D4B will be created again and not use BF04C2E8C73A43B2AE22E3E52875BB9B.

**Comment by thijsvanloef** [comment]
What happens if you remove the contents of the `6A5B1DE2340E4AE889CEDF02AB841D4B` folder (but keep the folder). And copy the contents of the `BF04C2E8C73A43B2AE22E3E52875BB9B` into the `6A5B1DE2340E4AE889CEDF02AB841D4B` folder?

**Comment by larrydemons** [comment]
black screen and keep loading

**Comment by thijsvanloef** [comment]
This reddit comment might help:
https://www.reddit.com/r/Palworld/comments/19aqk72/comment/kit6s0l/?utm_source=share&utm_medium=web2x&context=3

**Comment by JustusPan** [comment]
encounter same phenomenon as @larrydemons

**Comment by DrokeRavens** [comment]
> encounter same phenomenon as @larrydemons after copy contents to new folder

Had the same problem.
Follow these steps: 
- Delete any save files on server.
- Start the server, it will generate a save file, lets take for example the folder name A000.
- Stop the server, make sure nothing is running otherwise = black screen
- Go to your old backup called B000.
- Rename B000 to A000.
- Upload your folder to server 
- Start the server

**Comment by thijsvanloef** [comment]
@larrydemons do you still need assistance or has the issue been resolved?

**Comment by Ericwww** [comment]
Well, I found the [solution](https://bbs.nga.cn/read.php?tid=39075608&rand=541) on a gaming forum in China.
It looks like you still need to modify `/home/ubuntu/palworld-server-docker/palworld/Pal/Saved/Config/LinuxServer/GameUserSettings.ini`.

Currently I'm trying to figure out how to make the docker image support starting directly from existing data. #96
