### ISSUE TITLE
Invalid Page Size on ARM

### ISSUE THREAD

**Issue by paulwer** [thijsvanloef/palworld-server-docker#397]
## Describe the bug

*****EXECUTING USERMOD*****
usermod: no changes
Only ARM64 hosts with 4k page size is supported.

## To Reproduce

Install on Oracle Cloud Free tier

## Expected behavior

Working

## Actual behavior

container restarts

## Request
What do I need to change to make it work on arm64

**Comment by sonroyaalmerol** [comment]
Page size is set on kernel compile time. The only way to make it work would be to change the OS image used by your Oracle instance. Ubuntu is a known working image with a 4k page size. I suggest you recreate your Oracle instance with that image selected then try again.

**Comment by paulwer** [comment]
Are there any other ways, like rebuilding, because I am currently not able to switch the OS.

Thanks 
Paul
