### ISSUE TITLE
Add ENV Variable to Enable RCON and set RCON port

### ISSUE THREAD

**Issue by xHyperElectric** [thijsvanloef/palworld-server-docker#40]
It would be awesome if there was an option to enable RCON and set the RCON port.

**Describe the solution you'd like**
An ENV Variable option to enable RCON and set its port. i.e. `ENABLE_RCON = true` and `RCON_PORT = 25575`. RCON can be set in "Pal/Saved/Config/LinuxServer/PalWorldSettings.ini" with these values from the .ini: "RCONEnabled=False, RCONPort=25575".

**Comment by xHyperElectric** [comment]
I would love to be able to edit any value in the "Pal/Saved/Config/LinuxServer/PalWorldSettings.ini" file, but I'm not sure the best way to do it. Maybe with some guidance, I could submit a PR. Would the best way to handle it just be `cd /.../Pal/Saved/Config/LinuxServer/` and something like: `sed -i 's/RCONEnabled=False/RCONEnabled=true/' PalWorldSettings.ini`?

**Comment by thijsvanloef** [comment]
@xHyperElectric Probably just `sed` the RCONEnabled in the `DefaultPalServerSettings.ini` and after all the changes have been made, copy it to the `PalServerSettings.ini` in `/.../Pal/Saved/Config/LinuxServer/`

**Comment by xHyperElectric** [comment]
What would be the best way to allow all of the settings in PalWorldSettings.ini to be changed in the docker file?

**Comment by thijsvanloef** [comment]
@xHyperElectric Feel free to open a PR even if you are unsure, we can always take a look at it together :)

**Comment by thijsvanloef** [comment]
@xHyperElectric most user friendly way would be via environment variables

**Comment by xHyperElectric** [comment]
So is it practical to make an environment variable option for all 62 options?

**Comment by thijsvanloef** [comment]
@xHyperElectric no not really practical, that is partly the reason i've yet to work on it, because there isn't really any other "user friendly" way

**Comment by xHyperElectric** [comment]
I think the best way to do it is to add a second Volume for Server Config Storage and have the PalWorldSettings.ini file in there and it overwrites the one in `/.../Pal/Saved/Config/LinuxServer/`. I think it's [recommended to use a bind-mount](https://stackoverflow.com/questions/61202608/recommended-way-to-provide-configuration-files-to-docker-containers) for this but I am by no means a docker expert.

**Comment by Twinki14** [comment]
On theorizing, it may be possible to dynamically search for environment variables based off `DefaultPalServerSettings.ini`

For example, given this setting found in `DefaultPalServerSettings.ini`, `bEnablePlayerToPlayerDamage`, check if a value is in `B_ENABLE_PLAYER_TO_PLAYER_DAMGE`, and if so, write to `PalServerSettings.ini`

This would require generating a `PalServerSettings.ini` on init. You could loop through all given settings in `DefaultPalServerSettings.ini` using regex, then see if the given setting has a value in the environment, and then write each setting as you loop to `PalServerSettings.ini`, defaulting to the default value if the environment variable isn't present

**Comment by avail** [comment]
This is unreal engine, meaning https://docs.unrealengine.com/5.2/en-US/configuration-files-in-unreal-engine/ applies.
As such ("Override Configuration from the Command-line" section), you are able to override specific values via commandline

**Comment by Twinki14** [comment]
> This is unreal engine, meaning https://docs.unrealengine.com/5.2/en-US/configuration-files-in-unreal-engine/ applies. As such ("Override Configuration from the Command-line" section), you are able to override specific values via commandline

Even better, need to figure out the right syntax for palworld-specific ini settings
