### ISSUE TITLE
Create broadcast function

### ISSUE THREAD

**Issue by Dashboy1998** [thijsvanloef/palworld-server-docker#400]
**Is your feature request related to a problem? Please describe.**
Currently broadcast is called from many places.

**Describe the solution you'd like**
Make a function so if it is ever changed you only need to update in one location.
Validate the message has no white space
Validate the message is only ASCII 

**Describe alternatives you've considered**
Currently we just call RCON as needed

**Comment by Luatan** [comment]
I think it would also be nice, if the function for broadcast replaces the whitespaces directly, so the one who calls it does not have to worry about it. This way we can change the handling of the whitespaces at a single place if the bug gets fixed.
