### ISSUE TITLE
Multicore Server

### ISSUE THREAD

**Issue by batscs** [thijsvanloef/palworld-server-docker#406]
**Is your feature request related to a problem? Please describe.**
Even though the docker container itself is not limited in cpu usage it is using only 100% (sometimes up to ~120% for very short peaks). I suspect this being a fault of the PalServer on Linux itself and not necesserily this docker image.

**Describe the solution you'd like**
According to this [Steam Discussion](https://steamcommunity.com/app/1623730/discussions/0/4132683013937974032/) it seems like the issue could be fixed by adding flags when starting the `/palworld/PalServer.sh` file on startup of the container.

To not directly edit the file, could there be maybe an environment variable or something for the docker-compose.yml to add custom flags, in this case it would be: `-useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS` and directly pass them on each startup in the docker image.

**Additional context**
Running the docker container on a Ubuntu 22.04 Server, only one out of six possible cores is being used, even though no other process really uses cpu.

**Comment by sonroyaalmerol** [comment]
> To not directly edit the file, could there be maybe an environment variable or something for the docker-compose.yml to add custom flags, in this case it would be: `-useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS` and directly pass them on each startup in the docker image.

This is exactly what the MULTITHREADING env variable is doing. If that env var does nothing for you, then I'm guessing something other than your CPU is causing a bottleneck. Either that, or some kind of bug/error with the PalServer itself. If that's the case, then there's nothing we can do about it.

**Comment by batscs** [comment]
When I have `MULTITHREADING: true` I get following erorr message after `docker-compose config`
```
services.palworld.environment.MULTITHREADING contains true, which is an invalid type, it should be a string, number, or a null
```
I was using `"true"`, but apparently that is not working correctly, as my server is not using multithreading. I know this is not directly an issue with this palserver project, but do you have any idea on how to fix this or what is causing the issue?

**Comment by Phelms215** [comment]
Make it 

`MULTITHREADING=true`

**Comment by batscs** [comment]
This has fixed my issue. In case anyone else experiences the same behaviour, I changed the environment section in the docker-compose to this:
```yml
      environment:
        - PUID=1000
        - PGID=1000
        - PORT=8211 # Optional but recommended
        - PLAYERS=16 # Optional but recommended
        - SERVER_PASSWORD=mypassword # Optional but recommended
        - MULTITHREADING=true
        - RCON_ENABLED=true
        - RCON_PORT=25575
        - TZ=UTC
        - ADMIN_PASSWORD=adminPasswordHere
        - COMMUNITY=true  # Enable this if you want your server to shw up in the community servers tab, USE WITH SERVER_PASSWORD!
        - SERVER_NAME=myservername
        - SERVER_DESCRIPTION=mydescription
```
