### ISSUE TITLE
Configuration file will be regenerated on every reboot (/Pal/Binaries/Linux/steam_appid.txt)

### ISSUE THREAD

**Issue by vwer** [thijsvanloef/palworld-server-docker#415]
Configuration file will be regenerated on every reboot (/Pal/Binaries/Linux/steam_appid.txt)

**Comment by thijsvanloef** [comment]
Hi! I'm having trouble understanding what the exact issue is you are facing. The steam_appid.txt should not change every reboot, but what is the issue if it does?

**Comment by thijsvanloef** [comment]
That is because SteamCMD will check for an update every restart, if (for some reason) you don't want that to happen, you can use `UPDATE_ON_BOOT=false`
Closing this issue, as this is intended behaviour.
