### ISSUE TITLE
Adding release version to list of Variable in readme

### ISSUE THREAD

**Issue by MrCBlade** [thijsvanloef/palworld-server-docker#434]
**Is your feature request related to a problem? Please describe.**

Too many Variable to keep track of with what updates they are in. 

**Describe the solution you'd like**

Add Releases versions to the README.md page. If using an older version you can see what works vs new. Also what to add on new updates.

**Describe alternatives you've considered**

Add new row after "Allowed Values" and add "Version Add" or "Releases Version"

**Additional context**

Variable | Info | Default Values | Allowed Values | Added In Version
or
Variable | Info | Default Values | Allowed Values | Releases Version

**Comment by Dashboy1998** [comment]
> Variable | Info | Default Values | Allowed Values | Added In Version 
> or 
> Variable | Info | Default Values | Allowed Values | Releases Version

My issue with adding the Releases Version or Added In Version is that only tells you when it was added not the acceptable value for the given version. As an example prior to 0.28.0 AUTO_REBOOT_WARN_MINUTES could not be 0.


> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> Add Releases versions to the README.md page. If using an older version you can see what works vs new. Also what to add on new updates.

If you want to see the README.md for a given release then select the release tag

![image](https://github.com/thijsvanloef/palworld-server-docker/assets/18587674/9990611f-b295-4bb2-af77-cb7da88204fc)

**Comment by MrCBlade** [comment]
maybe do

Variable | Info | Default Values | Allowed Values | Added In Tag

at least anyone can know when it was added and can go see the releases page and find the tag number to read the details of why or who added it.

it's just something simple. As for the branches didn't know it could be used like that thanks for the tip

**Comment by Dashboy1998** [comment]
> at least anyone can know when it was added and can go see the releases page and find the tag number to read the details of why or who added it.

That makes sense because then you can at least see when a feature was added so to speak so you can decide if you want to upgrade from X to Y.
