### ISSUE TITLE
Portainer generating exit code 

### ISSUE THREAD

**Issue by itsanderz** [thijsvanloef/palworld-server-docker#444]
No longer able to run docker image in portainer. 

Generates exit code err 

![erererrereer](https://github.com/thijsvanloef/palworld-server-docker/assets/136952035/f3af6971-347a-487f-b69e-c1a1c9d60d65)

**Comment by Dashboy1998** [comment]
I am running in portainer and I have no issues.

Please post the logs for the container.

What version of the image are you running?
What is your OS?
What version of docker are you using?
What version of portainer are you using?

**Comment by itsanderz** [comment]
The latest version

Ubuntu 23

the latest version of docker and portainer

****EXECUTING USERMOD****
usermod: no changes
chown: cannot access '/palworld': No such file or directory
/palworld is not writable.

**Comment by Dashboy1998** [comment]
Are you binding a volume to /palworld in the container?

Does your container have the chown capability?

**Comment by thijsvanloef** [comment]
Closing the issue as there has been no more response
