### ISSUE TITLE
Palsettings ini keeps resetting

### ISSUE THREAD

**Issue by CirusTV** [thijsvanloef/palworld-server-docker#447]
When attempting to change the palworldsettings.ini file (docker shut down) it seems to overwrite on boot. Im new to this so please excuse my ignorance. any help would be appreciated. INFORMATION: Running on latest debian distro + casaOS as i also run a few minecraft servers. Apologies if this is covered or simple ive been searching for days!

**Comment by thijsvanloef** [comment]
Hi @CirusTV, if you are not using environment variables to set the game settings: https://palworld-server-docker.loef.dev/getting-started/configuration/game-settings, but instead want to manually change the PalWorldSettings.ini. You would have to set `DISABLE_GENERATE_SETTINGS=true`

**Comment by thijsvanloef** [comment]
I've noticed this question some more lately, and concluded that there is not enough information regarding this in the docs, I've added the following page: https://palworld-server-docker.loef.dev/known-issues/#palworldsettingsini-keeps-resetting
