### ISSUE TITLE
Debug logs?

### ISSUE THREAD

**Issue by JakeCooper** [thijsvanloef/palworld-server-docker#45]
**Is your feature request related to a problem? Please describe.**
Got it running locally, and attempting to run it on Railway.app. Seems it just can't connect, and wondering if there's a way to turn on debug logging

**Describe the solution you'd like**
An environment variable for: LOG_LEVEL=debug,warn,error

**Describe alternatives you've considered**

**Additional context**

**Comment by thijsvanloef** [comment]
Currently the Palworld Dedicated server does not output any logging, this is not something I can fix.

**Comment by thijsvanloef** [comment]
@JakeCooper Is it ok if I close this issue?

**Comment by JakeCooper** [comment]
Yup all good! Will close myself
