### ISSUE TITLE
Update for v0.1.5.0

### ISSUE THREAD

**Issue by MusclePr** [thijsvanloef/palworld-server-docker#458]
This is not bug.
The rcon port no longer listen from v0.1.5.0 without `-rcon` or `-rconport=` option.

and modified options.
`EpicApp=PalServer`  ---> `-publiclobby`
reference from https://tech.palworldgame.com/settings-and-operation/arguments

```diff
diff --git a/scripts/start.sh b/scripts/start.sh
index 4e014c9..1b826e2 100644
--- a/scripts/start.sh
+++ b/scripts/start.sh
@@ -65,6 +65,7 @@ isReadable "${STARTCOMMAND[0]}" || exit
 isExecutable "${STARTCOMMAND[0]}" || exit
 
 # Prepare Arguments
+STARTCOMMAND+=("-rcon")
 if [ -n "${PORT}" ]; then
     STARTCOMMAND+=("-port=${PORT}")
 fi
@@ -74,7 +75,7 @@ if [ -n "${QUERY_PORT}" ]; then
 fi
 
 if [ "${COMMUNITY,,}" = true ]; then
-    STARTCOMMAND+=("EpicApp=PalServer")
+    STARTCOMMAND+=("-publiclobby")
 fi
 
 if [ "${MULTITHREADING,,}" = true ]; then
```

**Comment by urbenlegend** [comment]
Hmmm, I wonder if this is probably why I am still experiencing symptoms from this closed bug: https://github.com/thijsvanloef/palworld-server-docker/issues/449#issuecomment-1965751390

**Comment by dualznz** [comment]
yea im getting the constant logging from rcon port not being open when it is

**Comment by bostrt** [comment]
I've submitted a PR for the RCON issue: https://github.com/thijsvanloef/palworld-server-docker/pull/459

**Comment by dualznz** [comment]
yup i implemented that into my start.sh file but i was still getting the flag error, so i commented out the `Waiting for RCON port to open to show player logging...` line in `/home/steam/server/player_logging.sh` then it wont come up all the time, it appears 0.1.5 broke alot of things.

also noticed that when logged into in-game rcon, you no longer see the connected player in the `escape` menu

**Comment by MusclePr** [comment]
add `bShowPlayerList=True` in `PalWorldSettings.ini` from v0.1.5.0

**Comment by chowhi123** [comment]
@43414d  We also need to add new variable bShowPlayerList=True to DefaultPalWorldSettings.ini. I don't know how to make changes using git. Could you help me?

**Comment by MusclePr** [comment]
PR created for support the bShowPlayerList in #461

**Comment by MusclePr** [comment]
> The cause of the problem where RCON is not enabled from .ini has been identified.
> I will fix it as soon as possible.

There is an official answer.
