### ISSUE TITLE
`docker-compose` example should include version

### ISSUE THREAD

**Issue by jmctune** [thijsvanloef/palworld-server-docker#46]
## Describe the bug

The `docker-compose.yml` example does not work out of the box.

It needs a `version` designated at the top.

ex:

```
version: "3.7"
```

## To Reproduce

```
% docker-compose up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'palworld'
```

## Expected behavior

Stack should stand up.

## Screenshots

N/A

## Desktop (please complete the following information):

Not necessary.

## docker-compose.yml contents

Using the default.

## Container/Host Logs

N/A

## Additional context

N/A

**Comment by thijsvanloef** [comment]
Hi @jmctune, version does not need to be specified in docker-compose.yml files, this option has been deprecated.

> Update in 2021: The new Docker Compose spec supports not defining a version property and is the recommended way to go moving forward. It supports both v2 and v3 properties.

I would suggest updating your docker version and using Compose V2: https://docs.docker.com/compose/migrate/
