### ISSUE TITLE
rcon 127.0.0.1:25575: connect: connection refused

### ISSUE THREAD

**Issue by Muswc** [thijsvanloef/palworld-server-docker#468]
## Describe the bug

When I start the server and enter the rcon command, I get the connection refused error

## Screenshots

![image](https://github.com/thijsvanloef/palworld-server-docker/assets/51782348/7fb8a6e3-c804-41e8-ba94-0f18e96b3121)

## OS information

- OS:  Ubuntu 22.04.3 LTS
- Palworld Version:  1.15.0
- Docker Image Version:  latest-arm64

## Hardware information

- CPU:  aarch64
- Memory:  24gb

## docker-compose.yml contents

![image](https://github.com/thijsvanloef/palworld-server-docker/assets/51782348/a2a57b42-de73-460b-b0de-f816da87279e)

# docker-compose.yml contents here
```

## Container/Host Logs

```log
<!-- Insert logs here -->
```

**Comment by thijsvanloef** [comment]
Please use the `latest` tag, instead of the `latest-arm64`, the `latest-arm64` tag has been deprecated and will no longer be updated. The `latest` tag now also supports arm64, and should resolve your issue.

**Comment by Muswc** [comment]
@thijsvanloef 
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/51782348/dd040c47-c84b-40be-9ef4-3242a8201929)
Am I doing something wrong? I didn't do anything except change the tag

**Comment by thijsvanloef** [comment]
I believe it grabbed an existing latest image from your host, you can get the new image by running:

- `docker compose down --rmi all`
- `docker compose up -d`

**Comment by Muswc** [comment]
Thanks for your kind help

**Comment by thijsvanloef** [comment]
You are welcome!
