### ISSUE TITLE
Multiple issues after 1.5.0

### ISSUE THREAD

**Issue by trrbentley** [thijsvanloef/palworld-server-docker#472]
## Describe the bug

Having the following issues with the container:

- Cron Jobs not functioning
- Server no longer prompts for password when connecting
- Getting the following repeating message in the log:

cli: config: parse file: yaml: line 1: did not find expected key
cli: config: parse file: yaml: line 1: did not find expected key

## To Reproduce

I am using the following environment variables:

      environment:
         - PUID=1000
         - PGID=1000
         - PORT=8211 # Optional but recommended
         - PLAYERS=4 # Optional but recommended
         - SERVER_PASSWORD="XXXX" # Optional but recommended
         - MULTITHREADING=true
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - TZ=UTC
         - ADMIN_PASSWORD="XXXX"
         - COMMUNITY=false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         - SERVER_NAME="XXXX"
         - BACKUP_ENABLED=true
         - BACKUP_CRON_EXPRESSION=0 3 * * 3,7
         - OLD_BACKUP_DAYS=30
         - DELETE_OLD_BACKUPS=true
         - AUTO_UPDATE_ENABLED=true
         - AUTO_UPDATE_CRON_EXPRESSION=0 6 * * *
         - AUTO_UPDATE_WARN_MINUTES=5
         - AUTO_REBOOT_ENABLED=true
         - AUTO_REBOOT_WARN_MINUTES=5
         - AUTO_REBOOT_EVEN_IF_PLAYERS_ONLINE=true
         - AUTO_REBOOT_CRON_EXPRESSION=0 12 * * *
         - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/XXXX
         - DEATH_PENALTY=None
         - ENABLE_NON_LOGIN_PENALTY=false

## Expected behavior

Server should prompt for a password when connecting.
Server should reboot/update/backup according to cron

**Comment by thijsvanloef** [comment]
Please use server Password and admin password without the quotations if you are using `KEY=VALUE`. 
You can use quotations but you have to use the new way of setting variables as shown in the docker-compose.yml https://github.com/thijsvanloef/palworld-server-docker/blob/main/docker-compose.yml

**Comment by thijsvanloef** [comment]
Also just noticed that you use a comma in your cron expression, this has not been tested and may not work according to https://crontab.guru/#0_3_*_*_3,7

**Comment by trrbentley** [comment]
Apparently I need to go back to cron school, the cron should be 0 3 * * 3,0  (days are 0-6 not 1-7)

Removing the quotes fixed the password, which was strange because it *did* work before...

Thanks! :octocat:
