### ISSUE TITLE
Update backup for 0.2.0.6

### ISSUE THREAD

**Issue by Dashboy1998** [thijsvanloef/palworld-server-docker#520]
## Is your feature request related to a problem? Please describe

Currently we backup all of `/palworld/Pal/Saved` however palworld now has a backup function which saves inside `/palworld/Pal/Saved/SavedGames/0/0123456789ABCEF/backup`

## Describe the solution you'd like

Exclude `/palworld/Pal/Saved/SavedGames/0/0123456789ABCEF/backup` in our backup

## Describe alternatives you've considered

We could keep it but that's extra storage.

## Additional context

N/A

## Feature Report Checklist

- [x] I am willing to implement this feature

**Comment by MukiEX** [comment]
As a heads up, this might require implementation of the new server variable to the existing mapping function for environment variables:

- Palworld Variable: bIsUseBackupSaveData
- thijsvanloef Variable formatting: IS_USE_BACKUP_SAVE_DATA

But for clarity's sake, it might require something different like DISABLE_PALWORLD_SAVE_BACKUP to make it obvious that the server's still backing things up, just not using Pocket Pair's functionality for that feature.
