### ISSUE TITLE
Discord Server Update Complete Message Not Sending

### ISSUE THREAD

**Issue by xHyperElectric** [thijsvanloef/palworld-server-docker#528]
## Describe the bug

Originally I didn't have any special message for post update discord webhook and I wasn't getting any messages for post update. I changed the post update message via env variable and still didn't get an update message. So I also explicitly added a webhook url for post update (despite it being the same as all the other messages) but I still haven't gotten a post update message.

## Expected behavior

To receive a post update message in Discord

## Actual behavior

I receive a pre update message, but not an update complete message.

## Screenshots

![image](https://github.com/thijsvanloef/palworld-server-docker/assets/71343435/0aa4f1ea-e7cb-4e98-8409-280086e62872)

![image](https://github.com/thijsvanloef/palworld-server-docker/assets/71343435/ba5f6b30-31b0-4134-b308-2e02ed787747)

## OS information (IMPORTANT)

- OS:  TrueNAS (via docker)
- Palworld Version: 1.5.1, 2.0.6, 2.1.0
- Docker Image Version: 34.0, 35.0

## Additional context

DISCORD_POST_UPDATE_BOOT_MESSAGE: Server update complete! @Palworld

DISCORD_POST_UPDATE_BOOT_MESSAGE_URL: webhook url

## Bug Report Checklist

- [x] I searched for my issue on the [Known issues page](https://palworld-server-docker.loef.dev/known-issues)
- [x] I searched for my issue in the [Closed issues](https://github.com/thijsvanloef/palworld-server-docker/issues?q=is%3Aissue+is%3Aclosed)
- [x] I have included all relevant information required above.
- [ ] I am willing to fix this bug

**Comment by thijsvanloef** [comment]
@xHyperElectric Found the issue, implementing fix now :)
