### ISSUE TITLE
Could you add a env to disable .ini config file auto generation?

### ISSUE THREAD

**Issue by teamilkman** [thijsvanloef/palworld-server-docker#535]
sometime need to control the ini file manually

**Comment by thijsvanloef** [comment]
@teamilkman You can set the following environment variables:

`DISABLE_GENERATE_SETTINGS: true` -> disable the generation of PalWorldSettings.ini
`DISABLE_GENERATE_ENGINE: true` -> disable the generation of Engine.ini

Is that what you are looking for?
