### ISSUE TITLE
Strange things with the ENABLE_PLAYER_LOGGING  function and discord messages after the last update

### ISSUE THREAD

**Issue by TheKogoro** [thijsvanloef/palworld-server-docker#538]
Hello, i dont know if it's normal but i get a problem with the function "ENABLE_PLAYER_LOGGING"

Before, it's just say the name of the player from the server on discord and on the server broadcast and now, it make the steam player make login and unlog and after it put the ingame name with server user ID and steam ID on discord and server broadcast:

```
[2024-04-21 15:53:30] [LOG] Kogoro  executed the command. ShowPlayers

Kogoro  has joined

[2024-04-21 15:53:30] [LOG] Kogoro  executed the command. broadcast Kogoro__has_joined

Sending Discord json: {"embeds":[{"title":"Player Joined","description":"Kogoro  à rejoins le serveur!","color":52224}],"flags":0}

[2024-04-21 15:53:31] [LOG] Tanaka Lyanne joined the server. (User id: steam_76561198379551257)

[2024-04-21 15:53:45] [LOG] RCON executed the command. ShowPlayers

Kogoro  has left

[2024-04-21 15:53:45] [LOG] RCON executed the command. broadcast Kogoro__has_left

Tanaka Lyanne,2C17391D000000000000000000000000,76561198379551257 has joined

Sending Discord json: {"embeds":[{"title":"Player Left","description":"Kogoro  à quitté le serveur!","color":14614528}],"flags":0}

[2024-04-21 15:53:45] [LOG] RCON executed the command. broadcast Tanaka_Lyanne,2C17391D000000000000000000000000,76561198379551257_has_joined

Sending Discord json: {"embeds":[{"title":"Player Joined","description":"Tanaka Lyanne,2C17391D000000000000000000000000,76561198379551257 à rejoins le serveur!","color":52224}],"flags":0}

[2024-04-21 15:54:00] [LOG] RCON executed the command. ShowPlayers
```

I suppose something has changed after the last update , here is 2 picture of before update and after:

BEFORE:
![log player before](https://github.com/thijsvanloef/palworld-server-docker/assets/112748318/63df2678-5d15-47ea-82b5-5d3fc5077b0f)

AFTER:
![log player](https://github.com/thijsvanloef/palworld-server-docker/assets/112748318/2d90d32d-e2f8-46f2-ae1c-76b937a04e12)
![Capture](https://github.com/thijsvanloef/palworld-server-docker/assets/112748318/0d60282f-6937-4780-84d5-47caeda5e752)

Note that "Kogoro" is my steam name and Tanaka is the name of my character. i dont know why it make like a login/unlog of my Steam name and after resend same for the "server" and with the save ID and the steam ID.

the only way actually to have only one greetings (player name, save ID, steam ID) if i delete the lines "DISCORD_PLAYER_JOIN_MESSAGE" & "DISCORD_PLAYER_LEAVE_MESSAGE". before, all is activated i i didnt remember any problems. Note that as i say, before the update i only get on discord and ingame the Player name in the greetings and not full save ID and steam id with the player name.

**Comment by falkoro** [comment]
+1 I have the same.

**Comment by thijsvanloef** [comment]
Will look into it, thanks for reporting!
