### ISSUE TITLE
RCON doesnt work | cli: auth: rcon: dial tcp 127.21.0.2:25575: connect: connection refused

### ISSUE THREAD

**Issue by FurkanVG** [thijsvanloef/palworld-server-docker#55]
## Describe the bug
The new update should support RCON. But it doesnt.

Im using https://github.com/gorcon/rcon-cli to connect to the Palworld RCON. Everytime, doesnt matter if i try the localhost IP, the normla IP or the Docker IP, all resolve to Connection Refused.

## To Reproduce
1. Get RCON Client: https://github.com/gorcon/rcon-cli
2. Run client on localhost where Server runs
3. Enter Server IP and Port (in this case 25575)
4. Get Connection Refused Error

## Expected behavior
It should connect but refuses.

## Screenshots
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/68749298/0a811d5f-2c7e-4ab5-aa55-7999006b3edd)

## Desktop (please complete the following information):
- Linux Kali amd64

## docker-compose.yml contents

```services:
   palworld:
      image: thijsvanloef/palworld-server-docker
      restart: always
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - PORT=8211
         - PLAYERS=10
         - MULTITHREADING=true
         - ENABLE_RCON=true
         - RCON_PORT=25575
         - COMMUNITY=false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         - SERVER_PASSWORD=""
         - SERVER_NAME="Furkans Palworld"
         - ADMIN_PASSWORD="XXXXXXX!?"
      volumes:
         - /home/furkan/Palworld-Docker-Server:/palworld/

```

## Container/Host Logs
```
Success! App '2394010' fully installed.

*****CHECKING FOR EXISTING CONFIG*****

RCON_ENABLED=true

RCON_PORT=25575

*****STARTING SERVER*****

./PalServer.sh -port=8211 -players=10 -servername="Furkans Palworld" -serverpassword="" -adminpassword="XXXXXX!?" -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
```
It is also important to mention that i was able to successfully log in as Admin when i was in Palworld with my Admin Password.
Am i missing something?

**Comment by thijsvanloef** [comment]
If you were already running a server, please remove the <folder>/Pal/Saved/Config/LinuxServer/PalServerSettings.ini  and restart the server, the new PalServerSettings.ini should be generated allowing you to use RCON :)

**Comment by fisher60** [comment]
Possibly related to this, I noticed that even with RCON set to false, the container indicates it is running on startup

```yaml
environment:
         - PUID=1000
         - PGID=1000
         - PORT=8211 # Optional but recommended
         - PLAYERS=16 # Optional but recommended
         - MULTITHREADING=true
         - ENABLE_RCON=false
         - RCON_PORT=25589
         - ADMIN_PASSWORD="ThisIsNotMyRealPasswordMaybe"
         - COMMUNITY=false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
 ```

![image](https://github.com/thijsvanloef/palworld-server-docker/assets/39353605/5a795ed7-a60d-4ed7-be0a-1c8eda8380ff)

**Comment by thijsvanloef** [comment]
Yes that is my bad Variable should be RCON_ENABLED, i've changed the examples

**Comment by NepPure** [comment]
> PalServerSettings.ini

@thijsvanloef 
I didn't find `PalServerSettings.ini`, do you mean `PalWorldSettings.ini`?

**Comment by FurkanVG** [comment]
> If you were already running a server, please remove the /Pal/Saved/Config/LinuxServer/PalServerSettings.ini and restart the server, the new PalServerSettings.ini should be generated allowing you to use RCON :)

Hey :)

As mentioned above, the file to delete was called `PalWorldSettings.ini` and not  `PalServerSettings.ini`. Once this was done and I rebooted my Server, it generated the file with content and also empty values (which is intended i think):

```
 cat PalWorldSettings.ini
; This configuration file is a sample of the default server settings.
; Changes to this file will NOT be reflected on the server.
; To change the server settings, modify Pal/Saved/Config/LinuxServer/PalWorldSettings.ini.
[/Script/Pal.PalGameWorldSettings]
OptionSettings=(Difficulty=None,DayTimeSpeedRate=1.000000,NightTimeSpeedRate=1.000000,ExpRate=1.000000,PalCaptureRate=1.000000,PalSpawnNumRate=1.000000,PalDamageRateAttack=1.000000,PalDamageRateDefense=1.000000,PlayerDamageRateAttack=1.000000,PlayerDamageRateDefense=1.000000,PlayerStomachDecreaceRate=1.000000,PlayerStaminaDecreaceRate=1.000000,PlayerAutoHPRegeneRate=1.000000,PlayerAutoHpRegeneRateInSleep=1.000000,PalStomachDecreaceRate=1.000000,PalStaminaDecreaceRate=1.000000,PalAutoHPRegeneRate=1.000000,PalAutoHpRegeneRateInSleep=1.000000,BuildObjectDamageRate=1.000000,BuildObjectDeteriorationDamageRate=1.000000,CollectionDropRate=1.000000,CollectionObjectHpRate=1.000000,CollectionObjectRespawnSpeedRate=1.000000,EnemyDropItemRate=1.000000,DeathPenalty=All,bEnablePlayerToPlayerDamage=False,bEnableFriendlyFire=False,bEnableInvaderEnemy=True,bActiveUNKO=False,bEnableAimAssistPad=True,bEnableAimAssistKeyboard=False,DropItemMaxNum=3000,DropItemMaxNum_UNKO=100,BaseCampMaxNum=128,BaseCampWorkerMaxNum=15,DropItemAliveMaxHours=1.000000,bAutoResetGuildNoOnlinePlayers=False,AutoResetGuildTimeNoOnlinePlayers=72.000000,GuildPlayerMaxNum=20,PalEggDefaultHatchingTime=72.000000,WorkSpeedRate=1.000000,bIsMultiplay=False,bIsPvP=False,bCanPickupOtherGuildDeathPenaltyDrop=False,bEnableNonLoginPenalty=True,bEnableFastTravel=True,bIsStartLocationSelectByMap=True,bExistPlayerAfterLogout=False,bEnableDefenseOtherGuildPlayer=False,CoopPlayerMaxNum=4,ServerPlayerMaxNum=32,ServerName="Default Palworld Server",ServerDescription="",AdminPassword="",ServerPassword="",PublicPort=8211,PublicIP="",RCONEnabled=true,RCONPort=25575,Region="",bUseAuth=True,BanListURL="https://api.palworldgame.com/api/banlist.txt")
```
Testing again with AARCON, i was successfully able to connect to the Docker Palworld Server with ONLY the Docker IP:

`./ARRCON -H 172.21.0.2 -P 25575 -p verysecretpassword`

Thanks for the tip!

**Comment by Shiratsui** [comment]
I get the same error
It happens when migrate server (I used to host my server on gamever, and now I wont to host it locally)

It solved when deleting worldOption.sav file in Pal/Saved/SaveGames/0/XXXXX
Full path would be `Pal/Saved/SaveGames/0/XXXXX/worldOption.sav`

It seems like changing rcon password is not updating on worldOption.sav (maybe rcon settings configured inside this file)
