### ISSUE TITLE
BaseCampMaxNumInGuild

### ISSUE THREAD

**Issue by nevrion** [thijsvanloef/palworld-server-docker#563]
Hello. Since the update, it is possible to increase the maximum number of bases for a guild with the variable "BaseCampMaxNumInGuild". Since it apparently cannot yet be entered as an ENV variable, I would like to know how I can set it manually. When I add it to /Pal/Saved/Config/LinuxServer/PalworldSettings.ini, the entry is deleted after the server restart.

**Comment by thijsvanloef** [comment]
Thanks for letting me know, adding the option now

**Comment by thijsvanloef** [comment]
Has been added in version 0.38.1
