### ISSUE TITLE
Rubber banding on client side

### ISSUE THREAD

**Issue by tylerlucas** [thijsvanloef/palworld-server-docker#569]
## Describe the bug

Client devices are experiencing rubber-banding frequently (multiple times per minute). 

## To Reproduce

Happens continually throughout world

## OS information (IMPORTANT)

- OS:  Proxmox>UbuntuVM>Docker
- Palworld Version:  3.1 (today's patch)
- Docker Image Version:  

## Hardware information (IMPORTANT)

- CPU:  12x core 10th gen i5 3.2ghz
- Memory:  32gb DDR4

## Additional context

Approx 40% memory consumed; 
CPU average around 55%

## Bug Report Checklist

- [x ] I searched for my issue on the [Known issues page](https://palworld-server-docker.loef.dev/known-issues)
- [x ] I searched for my issue in the [Closed issues](https://github.com/thijsvanloef/palworld-server-docker/issues?q=is%3Aissue+is%3Aclosed)
- [x ] I have included all relevant information required above.
- [ ] I am willing to fix this bug

**Comment by thijsvanloef** [comment]
Hi @tylerlucas Is this since the Sakurajima update?

**Comment by Shybella** [comment]
Yeah, noticed this too with the new update

**Comment by tylerlucas** [comment]
Really need to do a bare metal test on the same host and compare. Still
seeing it on my end with memory <50% and CPU at 60%

**Comment by Shybella** [comment]
I do not believe it's related to the docker image, official servers are
unstable and rubber band too.

**Comment by thijsvanloef** [comment]
Closing this issue, as it is not related to the image.
This is something that needs to be addressed by the Palworld devs.
