### ISSUE TITLE
unsupported config option fer services : 'palworld'

### ISSUE THREAD

**Issue by leekrr23** [thijsvanloef/palworld-server-docker#578]
docker compose version / docker compose version v2.28.1

https://github.com/thijsvanloef/palworld-server-docker/blob/main/docker-compose.yml
docker-compose.yml 

i using command : sudo docker-compose up -d

resulting
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'palworld'

whats matter? i dont know What did I do wrong?

![issue](https://github.com/thijsvanloef/palworld-server-docker/assets/174893347/d05603a1-935a-47e2-a9a6-3a6409b2ba9b)

**Comment by thijsvanloef** [comment]
Please use https://www.yamllint.com/ to make sure that after you've changed the docker-compose.yml, the syntax of the file is still valid
