### ISSUE TITLE
 image: thijsvanloef/palworld-test Proteted on Docker HUB

### ISSUE THREAD

**Issue by GuillaumeBarreau** [thijsvanloef/palworld-server-docker#58]
## Describe the bug

Hi amigo,

Thx for your work.

I have a question.

Recently, you changed the tag of your Docker image from thijsvanloef/palworld-server-docker to thijsvanloef/palworld-test in your Docker Compose file. The thijsvanloef/palworld-test image is protected, It cannot be used in comparison to thijsvanloef/palworld-server-docker.

I would like to know if you are in the process of modifying it, or if this is an error during testing.

or maybe I made a mistake.

**Comment by thijsvanloef** [comment]
Error during testing good catch! I've changed it
