### ISSUE TITLE
How to Configure and Use Mod in Docker Service?

### ISSUE THREAD

**Issue by BitsVal** [thijsvanloef/palworld-server-docker#583]
Hi. I tried placing the pak Mod files in the palworld/Pal/Content/Paks directory mounted by Docker, but it didn't work. Does it currently support Mod functionality? If it does, how should I correctly configure it?

**Comment by thijsvanloef** [comment]
Hi @BitsVal Could you share some more about your setup? 

- docker-compose,yml contents
- Logging
- Mod name
