### ISSUE TITLE
Add Support for Palguard in Palworld Server Docker

### ISSUE THREAD

**Issue by arturluizbr** [thijsvanloef/palworld-server-docker#594]
## Is your feature request related to a problem? Please describe

I'm looking to enhance the security of the Palworld server by integrating Palguard. Currently, there is no built-in support for Palguard in the Palworld server Docker setup, which limits the ability to protect servers against potential threats and manage permissions effectively.

## Describe the solution you'd like

I would like to see the Palworld server Docker setup include support for Palguard. This integration would allow server administrators to easily implement security measures and manage user permissions directly within the Docker environment.

## Describe alternatives you've considered

As an alternative, I considered manually configuring Palguard outside of the Docker container. However, this approach is less efficient and complicates the deployment process, especially for those who prefer to manage everything within Docker.

## Additional context

Adding Palguard to the Palworld server Docker would streamline the setup process for administrators looking to enhance security. You can find the Palguard repository here: [Palguard Repo](https://github.com/BloodDragon2580/Palguard).

**Comment by thijsvanloef** [comment]
Hi! it seems like the repository has been deleted
