### ISSUE TITLE
Disable ShowPlayers cron

### ISSUE THREAD

**Issue by patryk-matis** [thijsvanloef/palworld-server-docker#601]
## Describe the bug

Is it possible to disable cron for Showplayers?
It's not showing players anyway - it just spams the console:

## To Reproduce

1. Basic setup and just run the server

## Screenshots

![image](https://github.com/user-attachments/assets/c5222b42-df2c-4dd0-a055-94223c7e27fa)

## OS information (IMPORTANT)

- OS:  Ubuntu 24
- Palworld Version:  latest
- Docker Image Version:  latest

## Hardware information (IMPORTANT)

- CPU:  i5 12600k
- Memory:  16GB DDR5

## Bug Report Checklist

- [x] I searched for my issue on the [Known issues page](https://palworld-server-docker.loef.dev/known-issues)
- [x] I searched for my issue in the [Closed issues](https://github.com/thijsvanloef/palworld-server-docker/issues?q=is%3Aissue+is%3Aclosed)
- [x] I have included all relevant information required above.
- [ ] I am willing to fix this bug

**Comment by thijsvanloef** [comment]
You can set `ENABLE_PLAYER_LOGGING` to `false`
