### ISSUE TITLE
how to set PalWorldSettings.ini On k8s ?

### ISSUE THREAD

**Issue by chominnn** [thijsvanloef/palworld-server-docker#607]
I don't think I can access the root directory.

It runs normally when mounted using a volume in a different directory.
However, of course, the server settings are not applicable.

**[deploy.yaml]**
---
          volumeMounts:
            - mountPath: /palworld
              name: datadir
            - mountPath: /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini
              name: palworld-settings
              subPath: PalWorldSettings.ini
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: palworld-server-datadir
      - name: palworld-settings
        configMap:
          name: palworld-settings

**[configmap.yaml]**
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: palworld-settings
data:
  PalWorldSettings.ini: >-
    [/Script/OnlineSubsystemUtils.IpNetDriver]
    NetServerMaxTickRate=60

    [/Script/Pal.PalGameWorldSettings]

    OptionSettings=(
    Difficulty=Difficult,
    DayTimeSpeedRate=1.000000,
    NightTimeSpeedRate=1.000000,
    ExpRate=5.000000,
    PalCaptureRate=1.000000,
    PalSpawnNumRate=2.000000,

**[PV]**
---
![image](https://github.com/user-attachments/assets/f462a3c3-84d6-4019-ba1e-19c805f96054)

**[Error]**
---
![image](https://github.com/user-attachments/assets/728ff5ed-6bc7-4c69-b82d-d45c103900fe)

**Comment by thijsvanloef** [comment]
Hi @chominnn I would highly suggest you set the config options via de environment variables as shown in the config map example here: https://github.com/thijsvanloef/palworld-server-docker/blob/main/k8s/configmap.yaml

**Comment by chominnn** [comment]
> Hi @chominnn I would highly suggest you set the config options via de environment variables as shown in the config map example here: https://github.com/thijsvanloef/palworld-server-docker/blob/main/k8s/configmap.yaml

I think that config is not PalworldSettings.ini

i want Edit PalworldSettings.ini ( Difficult, Death Penalty etc..)

**Comment by thijsvanloef** [comment]
You can use any of these environment variables in the config map: 
https://palworld-server-docker.loef.dev/getting-started/configuration/game-settings

**Comment by chominnn** [comment]
> 다음 환경 변수를 config 맵에서 사용할 수 있습니다: https://palworld-server-docker.loef.dev/getting-started/configuration/game-settings

After looking at the contents, I added one more config map and applied it as below


        - mountPath: /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini
          name: palworld-settings
          subPath: PalWorldSettings.ini


An error has occurred in the text.
![image](https://github.com/user-attachments/assets/e64e1a16-e43f-4e2f-826f-59d4de9911fd)


I referred to the following, but an error occurs to me

https://github.com/thijsvanloef/palworld-server-docker/issues/202

**Comment by MeCode4Food** [comment]
Have you set `DISABLE_GENERATE_SETTINGS` to true?

**Comment by chominnn** [comment]
> `DISABLE_GENERATE_SETTINGS`true로 설정하셨나요 ?

hello :)

Yes, I added it to the config map with reference to the example below.

But it didn't seem to work and create a default setting.
https://github.com/thijsvanloef/palworld-server-docker/blob/main/k8s/configmap.yaml

**Comment by chominnn** [comment]
> `DISABLE_GENERATE_SETTINGS`True로 설정하셨나요 ?

I'm embarrassed

I didn't know it was a disable option and set it to true.

Thank you for your help... T-T
