### ISSUE TITLE
Palworld Server not compatible with v0.3.12 and unable to update from v0.3.11.63395

### ISSUE THREAD

**Issue by lacky1991** [thijsvanloef/palworld-server-docker#631]
## Describe the bug

The Palworld server is not compatible with version v0.3.12, and the game cannot be updated to the correct version. The server is running version v0.3.11.63395, which causes compatibility issues with the latest available version (v0.3.12).

## To Reproduce

- Start with docker-compose with UPDATE_ON_BOOT=true
- The server is running version v0.3.11.63395.
. Attempting to update to version v0.3.12 fails due to compatibility issues.

## Expected behavior

The Palworld server should be compatible with the latest game version (v0.3.12)

**Comment by thijsvanloef** [comment]
Hi @lacky1991 I've noticed the same errors, doing the following seems to have fixed it:

- Shut down server
- Go to `palworld/steamapps`
- Delete `appmanifest_2394010.acf`
- Start the server

**Comment by lacky1991** [comment]
yes, thanks a lot.
