### ISSUE TITLE
Adding rcon-cli to the image

### ISSUE THREAD

**Issue by MSpreckels** [thijsvanloef/palworld-server-docker#64]
Hi there!

Love the docker image, been using it in my local homelab cluster to run palworld without any problems for my friends and I. Palworld, by default, offers you to enable rcon. I'd love to see the [rcon-cli](https://github.com/gorcon/rcon-cli) being added in the near future.

**Comment by thijsvanloef** [comment]
Release 0.11.0 fixes this issue, check the readme on how to use the rcon-cli https://github.com/thijsvanloef/palworld-server-docker?tab=readme-ov-file#using-rcon

**Comment by MSpreckels** [comment]
Thank you!
