### ISSUE TITLE
SteamAPI Initialization Issue During Server Startup

### ISSUE THREAD

**Issue by SORAPSYGA** [thijsvanloef/palworld-server-docker#7]
Hi there,

I'm encountering an issue during server startup where the SteamAPI fails to initialize before accessing Steam interfaces. The specific errors in the log are:

*****STARTING INSTALL/UPDATE*****tid(13) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/root/Steam/logs/stderr.txt'
Logging directory: '/root/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...*****STARTING INSTALL/UPDATE*****tid(12) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/root/Steam/logs/stderr.txt'
Logging directory: '/root/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) verifying install, progress: 3.89 (183811515 / 4729403737)
 Update state (0x5) verifying install, progress: 11.78 (557110360 / 4729403737)
 Update state (0x5) verifying install, progress: 19.76 (934597720 / 4729403737)
 Update state (0x5) verifying install, progress: 27.68 (1308946124 / 4729403737)
 Update state (0x5) verifying install, progress: 35.54 (1680807758 / 4729403737)
 Update state (0x5) verifying install, progress: 43.23 (2044514465 / 4729403737)
 Update state (0x5) verifying install, progress: 51.11 (2417006988 / 4729403737)
 Update state (0x5) verifying install, progress: 59.08 (2794106774 / 4729403737)
 Update state (0x5) verifying install, progress: 67.11 (3174075366 / 4729403737)
 Update state (0x5) verifying install, progress: 75.02 (3548194126 / 4729403737)
 Update state (0x5) verifying install, progress: 82.97 (3924164491 / 4729403737)
 Update state (0x5) verifying install, progress: 90.92 (4300113788 / 4729403737)
 Update state (0x5) verifying install, progress: 98.76 (4670725069 / 4729403737)
Success! App '2394010' fully installed.
./PalServer.sh -port=8211 -players=16
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
*****STARTING SERVER*****Shutdown handler: initalize.
Increasing per-process limit of core file size to infinity.
- Existing per-process limit (soft=18446744073709551615, hard=18446744073709551615) is enough for us (need only 18446744073709551615)
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
Setting breakpad minidump AppID = 2394010
[S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.

It seems that the server needs to wait for successful SteamAPI initialization before accessing Steam interfaces. I've attempted some adjustments, but the issue persists.

Any assistance in resolving this matter would be greatly appreciated.

**Comment by thijsvanloef** [comment]
I've encountered the same error, however it seems to still run the server as normal. Are you still able to join and play on the server?

**Comment by SORAPSYGA** [comment]
I have noticed that despite this error, the game can still connect normally. However, there is no change in the container logs. I am currently testing it. Thank you very much for creating the Docker image.

> I've encountered the same error, however it seems to still run the server as normal. Are you still able to join and play on the server?

**Comment by thijsvanloef** [comment]
I think (could be mistaken) that the fact there is no server output is a limitation that the Palworld devs need to find a fix for.

**Comment by zbellerose** [comment]
I can confirm the server is working fine even with those errors.

**Comment by thijsvanloef** [comment]
I'll still keep this issue open for visibility, however I do not believe this is something I can fix

**Comment by thijsvanloef** [comment]
I've added this to the known issues page on the GitHub Wiki, 
https://github.com/thijsvanloef/palworld-server-docker/wiki/Known-Issues

**Comment by MoryCorp** [comment]
Can confirm the server works very well even with this message : 

```
Increasing per-process limit of core file size to infinity.
- Existing per-process limit (soft=18446744073709551615, hard=18446744073709551615) is enough for us (need only 18446744073709551615)
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
Setting breakpad minidump AppID = 2394010
[S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
```

Been playing with friends for 24 hours and going
