### ISSUE TITLE
Failed to connect to RCON serverrcon: response too long

### ISSUE THREAD

**Issue by mynam333** [thijsvanloef/palworld-server-docker#75]
When I type "docker exec -it palworld-server rcon-cli" into the console, I get this error message.

Error message:
Failed to connect to RCON serverrcon: response too long

May I know what's going on?

**Comment by fryfrog** [comment]
I had to enable RCON in my `./Pal/Saved/Config/LinuxServer/PalWorldSettings.ini`, maybe as simple as that?

**Comment by thijsvanloef** [comment]
Hi @mynam333 RCON was added in an updated version of my docker image, if you only restart the container, the new image will not be downloaded and thus, you will not be able to use RCON. Please update the image:

- `docker stop palworld-server`
- `docker rm palworld-server`
- `docker rmi thijsvanloef/palworld-server-docker`
- `docker compose up -d`

If you mounted the palworld folder to your system, you should not lose any data. However it is always a good idea to backup your savefiles just to be sure.

**Comment by AntiMoron** [comment]
@thijsvanloef Hi, I found every time I start a container on a server, it will download some large content(4gb) for quite a long time. Can we optimize to cache the updated stuff to some volumn on the server?

![image](https://github.com/thijsvanloef/palworld-server-docker/assets/6587734/90eaeedd-a9f6-4ee6-bb93-dd40ea53fbc9)

**Comment by thijsvanloef** [comment]
@AntiMoron Please open a different issue, please include as much information as you can: https://github.com/thijsvanloef/palworld-server-docker/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

**Comment by thijsvanloef** [comment]
@mynam333 are you still experiencing this issue, or can I close the issue?
