### ISSUE TITLE
Questions about using RCON

### ISSUE THREAD

**Issue by JooCheolWoo** [thijsvanloef/palworld-server-docker#85]
When using Broadcast among RCON's functions, only one word is transmitted. Can it be sent as a sentence?

As an example, if I use 
docker exec -it palworld-server rcon-cli Broadcast "Hello world"
only Hello is transmitted.

Also, I wonder if support is available for Korean.

**Comment by MSpreckels** [comment]
Hey there,

I'm seeing the same issue. I've tried a lot of different variations of the command too.

e.g.
Hello world
"Hello world"
'Hello world'
'"Hello world"'
"'Hello world'"

It seems like there is a bug in the palworld server where it only takes the first word. On my server I've settled with using underscore as a spacer between words.

**Comment by thijsvanloef** [comment]
This seems to be an issue with the broadcast command. When using /Broadcast in game, it will also ignore the second word.
I do not believe this is an issue with my code.

**Comment by thijsvanloef** [comment]
@JooCheolWoo I've added this to known issues: https://github.com/thijsvanloef/palworld-server-docker/wiki/Known-Issues#broadcast-command-can-only-send-1-word

**Comment by thijsvanloef** [comment]
@JooCheolWoo I am not at liberty to check if Korean is a supported language, if it is not, I would suggest opening a feature request here: https://forms.pocketpair.jp/palworld
