### ISSUE TITLE
docker-compose up failed

### ISSUE THREAD

**Issue by FunkyGod** [thijsvanloef/palworld-server-docker#88]
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/39259580/a88beee4-ff0a-481f-a420-5bc25f37db61)
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/39259580/f782e230-7196-4709-b9d8-c3f056eed82d)
docker-compose up, error happend.
please help me

**Comment by thijsvanloef** [comment]
The S_API FAIL is a known issue and should not impact the server, you can play as normally:
https://github.com/thijsvanloef/palworld-server-docker/wiki/Known-Issues#s_api-fail

**Comment by FunkyGod** [comment]
> The S_API FAIL is a known issue and should not impact the server, you can play as normally: https://github.com/thijsvanloef/palworld-server-docker/wiki/Known-Issues#s_api-fail

![image](https://github.com/thijsvanloef/palworld-server-docker/assets/39259580/86b3b800-a30d-47c3-a301-e784db9514b5)

help!

**Comment by FunkyGod** [comment]
help!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Thijs van ***@***.***&gt;; 
发送时间: 2024年1月24日(星期三) 晚上9:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [thijsvanloef/palworld-server-docker] docker-compose up failed (Issue #88)





 
Closing this issue, feel free to reopen if you are not able to connect to the server
 
&mdash;
